In [1]:
import pandas as pd

In [3]:
crime=pd.read_excel(r"C:\Users\krebi\Downloads\Crime_Data.xlsx")

In [4]:
# crime.info()
crime.describe()
crime.shape

(549999, 22)

In [ ]:
# ANALYZING DUBLICATES IN COLUMNS
# # a=crime.groupby("ID").count()
# a=crime.groupby("Case Number").count()
# # a.apply(display)
# # b=crime["Case Number"].value_counts()
# # c=b[b>1].index
# # d=crime[crime["Case Number"].isin(c)]
# # display(d)
# # b=crime["Case Number"].value_counts()  #it has dublicates 1037
# # b=crime["Block"].value_counts() 
# # c=b[b>1].index
# # d=crime[crime["Block"].isin(c)]
# display(a)
# a=crime.groupby("Case Number").count()  #it has 565 dublicates
# a=crime.groupby("Block").count()
# b=crime["Block"].value_counts() #max block 100x wohare st,in this block theft is happen 627 times
# e=b.max()
# f=b[b==e].index
# g =crime[crime["Block"].isin(f)]
# display(g)
# grouped = g.groupby('Primary Type').size().reset_index(name='Count')
# display(grouped)
# grouped.shape
# e=b.max()
# f=b[b==e].index
# g =crime[crime["Case Number"].isin(f)]
# pd.set_option("display.max_rows", None) 
# display(g)

,ID,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
Case Number,,,,,,,,,,,,,,,,,,,,,
01G050460,1,1,1,1,1,1,1,1,1,1,...,0,0,1,1,1,1,1,1,1,1
A417216,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
B003173,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
B430081,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
B780332,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Y293970,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Y449586,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Z291330,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Z420357,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Z582023,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [7]:

#THIS CODE DELETE THE DUBLICATES IN THE CASE NUMBER BY TIME
duplicate = crime[crime.duplicated(subset=['Case Number'], keep=False)]
crime = crime.sort_values(by=['TIME'])
crime = crime.drop_duplicates(subset=['Case Number'], keep='first')
crime.shape

(549434, 23)

In [40]:
display(duplicate[['Case Number', 'TIME']])

       Case Number      TIME
7115      JG499426  17:22:00
13711     JG499426  17:16:00
17153     JG499426  20:52:00
20390     JG446325  14:25:00
20881     JG446325  15:43:00
...            ...       ...
340114    HR411763  03:00:00
340166    HY551250  06:05:00
340372    HY106072  17:53:00
340702    HK509310  11:35:00
340840    HS148489  18:28:00

[1037 rows x 2 columns]

In [5]:
#ALTER THE DATE COLUMN INTO DATE AND TIME AND DATE FORMAT CHANGED FOR MY UNDERSTANDING
#  crime['Date'] = pd.to_datetime(crime['Date'])


crime['DATE'] = crime['Date'].dt.date
crime['TIME'] = crime['Date'].dt.time
crime['DATE']=crime['DATE'].apply(lambda x: x.strftime('%d-%m-%Y'))
crime.head(5)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN,25-08-2007,09:22:18
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)",24-05-2021,15:06:00
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)",26-06-2021,09:24:00
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,5,1162518.0,1925906.0,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)",09-11-2023,07:30:00
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)",12-11-2023,07:59:00

In [6]:
# ORIGINAL DATE COLUMN WHICH IS PRESENT IN THE DATASET DELETED
crime = crime.drop(columns=['Date'])
crime.head(3)

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
0,5741943,HN549294,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,2422,...,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN,25-08-2007,09:22:18
1,25953,JE240540,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,2515,...,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)",24-05-2021,15:06:00
2,26038,JE279849,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,1711,...,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)",26-06-2021,09:24:00

In [53]:
crime.head(10)
crime.info()

<class 'pandas.core.frame.DataFrame'>
Index: 549434 entries, 288617 to 414516
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549434 non-null  int64
 1   Case Number           549434 non-null  object
 2   Block                 549434 non-null  object
 3   IUCR                  549434 non-null  object
 4   Primary Type          549434 non-null  object
 5   Description           549434 non-null  object
 6   Location Description  547761 non-null  object
 7   Arrest                549434 non-null  bool
 8   Domestic              549434 non-null  bool
 9   Beat                  549434 non-null  int64
 10  District              549434 non-null  int64
 11  Ward                  213123 non-null  float64
 12  Community Area        214542 non-null  float64
 13  FBI Code              549434 non-null  object
 14  X Coordinate          542522 non-null  float64
 15  Y Coordinate          542522 non-null  float64
 16  Year                  549434 non-null  int64
 17  Updated On            549434 non-null  datetime64[ns]
 18  Latitude              542522 non-null  float64
 19  Longitude             542522 non-null  float64
 20  Location              542522 non-null  object
 21  DATE                  549434 non-null  object
 22  TIME                  549434 non-null  object
dtypes: bool(2), datetime64[ns](1), float64(6), int64(4), object(10)
memory usage: 93.3+ MB

In [9]:
#COUNTING NULL VALUES IN COLUMNS 
# Location Description =HAVING 1673 NAN VALUES
#X Coordinate,Y Coordinate,Latitude,Longitude,Location=HAVING 6912 NAN VALUES
#ward=HAVING 336311 NAN VALUES
#community area =having 334892 nn values
null_count = crime['District'].isnull().sum() 
print(f'Number of null values in latitude column: {null_count}')

Number of null values in latitude column: 0

In [63]:
null_rows = crime[crime['Location Description'].isnull()] 
print('Rows with null values in latitude column:') 
display(null_rows)

Rows with null values in latitude column:

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
40467,13264475,JG488390,026XX N Burling St,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,1935,...,11,NaN,NaN,2022,2023-11-03 15:41:45,NaN,NaN,NaN,11-08-2022,00:00:00
103776,13350317,JH129818,0000X W 71ST ST,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,NaN,False,False,731,...,11,1176970.0,1857910.0,2023,2024-01-29 15:40:30,41.765444,-87.626906,"(41.765444001, -87.626906181)",29-11-2023,00:00:00
197179,12944467,JG106464,067XX S PARNELL AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,722,...,11,NaN,NaN,2020,2023-01-07 15:41:08,NaN,NaN,NaN,17-02-2020,00:00:00
8471,13220618,JG435484,008XX N TRIPP AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,1111,...,11,NaN,NaN,2022,2023-09-24 15:42:42,NaN,NaN,NaN,28-06-2022,00:00:00
53624,13278433,JG504730,017XX W Le Moyne St,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,1433,...,11,1164571.0,1910151.0,2023,2023-11-17 15:40:26,41.909069,-87.670876,"(41.909069131, -87.670875681)",30-10-2023,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80045,13318125,JG552919,058XX N KINGSDALE AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,NaN,False,False,1711,...,11,NaN,NaN,2020,2023-12-25 15:40:48,NaN,NaN,NaN,17-05-2020,23:45:00
198024,9457402,HX110193,026XX N HALSTED ST,810,THEFT,OVER $500,NaN,False,False,1935,...,6,NaN,NaN,2014,2020-11-05 15:42:12,NaN,NaN,NaN,10-01-2014,23:45:00
33125,13254707,JG476038,118XX S PRINCETON AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,522,...,11,1176412.0,1826382.0,2023,2023-11-04 15:40:18,41.678940,-87.629896,"(41.678939502, -87.629895675)",17-03-2023,23:45:00
195359,12058553,JD241273,075XX S CALUMET AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,623,...,11,NaN,NaN,2020,2020-05-30 15:41:02,NaN,NaN,NaN,23-05-2020,23:50:00
155586,13425118,JH219372,080XX S PAULINA ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,611,...,11,1166410.0,1851385.0,2024,2024-04-12 15:41:46,41.747770,-87.665797,"(41.747769971, -87.665797486)",29-03-2024,23:58:00

In [8]:

crime.to_csv('crime_just.csv', index=False)

In [19]:
display(crime.iloc[:60,2:16])

,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate
288617,065XX S WESTERN AV,1310,CRIMINAL DAMAGE,TO PROPERTY,OTHER,False,False,832,8,NaN,NaN,14,1161535.0,1861313.0
52756,029XX S DR MARTIN LUTHER KING JR DR,890,THEFT,FROM BUILDING,APARTMENT,False,False,133,1,4.0,35.0,6,1179389.0,1885691.0
315612,030XX W WABANSIA AV,820,THEFT,$500 AND UNDER,STREET,False,False,1421,14,NaN,NaN,6,1155995.0,1911189.0
52754,011XX W NEWPORT AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1924,19,44.0,6.0,17,NaN,NaN
75599,024XX W 48TH ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,922,9,15.0,58.0,17,1160851.0,1872780.0
179458,038XX W WASHINGTON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1122,11,28.0,26.0,08B,1150858.0,1900145.0
9084,031XX N NARRAGANSETT AVE,1120,DECEPTIVE PRACTICE,FORGERY,SIDEWALK,False,False,2511,25,36.0,19.0,10,1133202.0,1920006.0
9085,066XX N MOZART ST,1242,DECEPTIVE PRACTICE,COMPUTER FRAUD,RESIDENCE,False,False,2412,24,50.0,2.0,11,1156129.0,1943876.0
145129,038XX W THOMAS ST,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,1112,11,27.0,23.0,5,1150752.0,1907066.0
343003,007XX N RIDGEWAY AV,820,THEFT,$500 AND UNDER,RESIDENCE PORCH/HALLWAY,False,True,1112,11,NaN,NaN,6,1151291.0,1904767.0
315621,015XX W TAYLOR ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,1231,12,NaN,NaN,26,1166287.0,1895626.0
266432,020XX W JARVIS AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,2424,24,NaN,NaN,7,1161511.0,1948737.0
52736,001XX W MAPLE ST,1900,OTHER NARCOTIC VIOLATION,INTOXICATING COMPOUNDS,RESIDENCE,False,True,1824,18,27.0,8.0,18,1174883.0,1907592.0
40397,026XX N CALIFORNIA AVE,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,RESIDENCE,False,False,1411,14,1.0,22.0,14,1157259.0,1917437.0
342962,009XX W LAWRENCE AV,281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,STREET,False,False,2024,20,NaN,NaN,2,1168955.0,1932101.0
499471,097XX S YATES AV,810,THEFT,OVER $500,RESIDENCE,False,False,431,4,NaN,NaN,6,1194154.0,1840505.0
439831,030XX W GUNNISON ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1713,17,NaN,NaN,14,1154906.0,1932098.0
342961,010XX W 104 PL,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,2232,22,NaN,NaN,7,1171423.0,1835564.0
75617,002XX E 38TH ST,4650,OTHER OFFENSE,SEX OFFENDER - FAIL TO REGISTER,PARK PROPERTY,True,False,212,2,3.0,35.0,26,1178637.0,1879851.0
139962,009XX W 31ST ST,1310,CRIMINAL DAMAGE,TO PROPERTY,STREET,False,False,913,9,11.0,60.0,14,1170183.0,1884289.0
75620,080XX S KILBOURN AVE,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,834,8,18.0,70.0,17,NaN,NaN
124388,066XX S MARYLAND AVE,1152,DECEPTIVE PRACTICE,ILLEGAL USE CASH CARD,RESIDENCE,False,False,321,3,20.0,42.0,11,1183034.0,1861240.0
75597,043XX N RICHMOND ST,1753,OFFENSE INVOLVING CHILDREN,SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER,RESIDENCE,False,True,1724,17,33.0,16.0,2,NaN,NaN
406321,015XX E 68 ST,820,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,332,3,NaN,NaN,6,1187807.0,1860170.0
406152,072XX S WOLCOTT AV,820,THEFT,$500 AND UNDER,STREET,False,False,735,7,NaN,NaN,6,1164987.0,1856402.0
343023,107XX S LA SALLE ST,810,THEFT,OVER $500,RESIDENCE-GARAGE,True,False,513,5,NaN,NaN,6,1177215.0,1833797.0
406039,009XX N TRUMBULL AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1121,11,NaN,NaN,7,1153243.0,1906085.0
343079,014XX N OAKLEY AV,610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,False,False,1424,14,NaN,NaN,5,1160841.0,1909871.0
122154,024XX N SEMINARY AVE,810,THEFT,OVER $500,STREET,False,False,1932,19,43.0,7.0,6,1168559.0,1916293.0
179505,002XX N HAMLIN BLVD,1310,CRIMINAL DAMAGE,TO PROPERTY,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,False,False,1122,11,28.0,26.0,14,1151029.0,1900696.0
40342,001XX E 47TH ST,620,BURGLARY,UNLAWFUL ENTRY,GROCERY FOOD STORE,False,False,215,2,3.0,38.0,5,1178100.0,1873900.0
499407,051XX W 64 PL,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,813,8,NaN,NaN,7,1142788.0,1861233.0
197246,015XX E 83RD ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER (SPECIFY),False,False,412,4,8.0,45.0,11,NaN,NaN
343067,064XX S EBERHART AV,810,THEFT,OVER $500,STREET,False,False,312,3,NaN,NaN,6,1180720.0,1862633.0
266493,001XX E WALTON ST,810,THEFT,OVER $500,STREET,False,False,1833,18,NaN,NaN,6,1176987.0,1906980.0
192495,010XX N SACRAMENTO AVE,560,ASSAULT,SIMPLE,SIDEWALK,False,False,1211,12,26.0,24.0,08A,1156188.0,1907011.0
266484,021XX N DAMEN AV,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,1432,14,NaN,NaN,17,1162714.0,1914344.0
52786,051XX N EAST RIVER RD,820,THEFT,$500 AND UNDER,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,1614,16,41.0,76.0,6,1116630.0,1933219.0
197241,014XX N SEDGWICK ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1821,18,27.0,8.0,17,NaN,NaN
112329,015XX S WABASH AVE,890,THEFT,FROM BUILDING,RESIDENCE,False,False,131,1,3.0,33.0,6,1177014.0,1892876.0
52784,033XX W 84TH PL,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,False,False,834,8,18.0,70.0,11,1155676.0,1848366.0
499420,001XX N PINE AV,820,THEFT,$500 AND UNDER,RESIDENCE,False,False,1523,15,NaN,NaN,6,1139523.0,1900383.0
179473,028XX S KOMENSKY AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,SCHOOL - PUBLIC BUILDING,False,False,1031,10,22.0,30.0,17,NaN,NaN
439978,012XX W NEWPORT AV,842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,1924,19,NaN,NaN,6,1167600.0,1923090.0
139969,010XX S CANAL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,COMMERCIAL / BUSINESS OFFICE,False,False,124,1,28.0,28.0,11,NaN,NaN
439945,013XX N WESTERN AV,810,THEFT,OVER $500,RESIDENCE PORCH/HALLWAY,False,False,1424,14,NaN,NaN,6,1160199.0,1909085.0
52777,009XX N CENTRAL AVE,810,THEFT,OVER $500,RESIDENCE,False,False,1524,15,37.0,25.0,6,1138851.0,1905567.0
406128,022XX N LAMON AV,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,2522,25,NaN,NaN,26,1143394.0,1914673.0
52804,010XX N FRANCISCO AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,HOSPITAL BUILDING / GROUNDS,False,False,1211,12,26.0,24.0,11,1156861.0,1906972.0
40410,027XX W HARRISON ST,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,True,1135,11,28.0,27.0,2,1158248.0,1897253.0
159849,104XX S MICHIGAN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,512,5,9.0,49.0,11,1178871.0,1835534.0
147413,019XX W 64TH ST,1120,DECEPTIVE PRACTICE,FORGERY,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,False,False,726,7,16.0,67.0,10,1164702.0,1862225.0
52675,089XX S DAUPHIN AVE,502P,OTHER OFFENSE,FALSE / STOLEN / ALTERED TRP,STREET,False,False,633,6,8.0,44.0,26,1183792.0,1845732.0
439685,036XX N NEWLAND AV,610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,False,False,1632,16,NaN,NaN,5,1129394.0,1923344.0
112275,067XX N CLARK ST,910,MOTOR VEHICLE THEFT,AUTOMOBILE,VEHICLE NON-COMMERCIAL,False,False,2432,24,49.0,1.0,7,1163812.0,1944780.0
85461,088XX S CARPENTER ST,920,MOTOR VEHICLE THEFT,ATTEMPT - AUTOMOBILE,STREET,False,False,2222,22,21.0,71.0,7,1170860.0,1846267.0
52674,037XX S VINCENNES AVE,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,VEHICLE NON-COMMERCIAL,False,False,212,2,4.0,35.0,11,1180854.0,1880094.0
40457,005XX N CENTRAL AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1523,15,37.0,25.0,14,1138937.0,1903092.0
112274,0000X N KILBOURN AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,GAS STATION,False,False,1113,11,28.0,26.0,14,1146387.0,1899777.0
315737,007XX N OGDEN AV,810,THEFT,OVER $500,STREET,False,False,1323,12,NaN,NaN,6,1168894.0,1905380.0

In [1]:
import pandas as pd
crimes=pd.read_csv(r"C:\Users\krebi\OneDrive\Desktop\chicago\crime_just.csv")
crimes.head(5)

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
0,1410349,G129070,065XX S WESTERN AV,1310,CRIMINAL DAMAGE,TO PROPERTY,OTHER,False,False,832,...,14,1161535.0,1861313.0,2001,17-08-2015 15:03,41.775116,-87.683386,"(41.775116246, -87.683386215)",04-03-2001,00:00:00
1,12943357,JG105846,029XX S DR MARTIN LUTHER KING JR DR,890,THEFT,FROM BUILDING,APARTMENT,False,False,133,...,6,1179389.0,1885691.0,2022,15-11-2023 15:41,41.841623,-87.617191,"(41.841622651, -87.617191438)",19-12-2022,00:00:00
2,1387139,G100055,030XX W WABANSIA AV,820,THEFT,$500 AND UNDER,STREET,False,False,1421,...,6,1155995.0,1911189.0,2001,17-08-2015 15:03,41.912095,-87.702352,"(41.912094921, -87.70235198)",18-01-2001,00:00:00
3,13277780,JG504858,011XX W NEWPORT AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1924,...,17,NaN,NaN,2013,15-11-2023 15:42,NaN,NaN,NaN,01-06-2013,00:00:00
4,12893837,JF475901,024XX W 48TH ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,922,...,17,1160851.0,1872780.0,2022,05-02-2024 15:40,41.806597,-87.685577,"(41.806597377, -87.685576958)",09-11-2022,00:00:00

In [2]:
display(crimes.iloc[:60,2:16])

,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate
0,065XX S WESTERN AV,1310,CRIMINAL DAMAGE,TO PROPERTY,OTHER,False,False,832,8,NaN,NaN,14,1161535.0,1861313.0
1,029XX S DR MARTIN LUTHER KING JR DR,890,THEFT,FROM BUILDING,APARTMENT,False,False,133,1,4.0,35.0,6,1179389.0,1885691.0
2,030XX W WABANSIA AV,820,THEFT,$500 AND UNDER,STREET,False,False,1421,14,NaN,NaN,6,1155995.0,1911189.0
3,011XX W NEWPORT AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1924,19,44.0,6.0,17,NaN,NaN
4,024XX W 48TH ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,922,9,15.0,58.0,17,1160851.0,1872780.0
5,038XX W WASHINGTON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1122,11,28.0,26.0,08B,1150858.0,1900145.0
6,031XX N NARRAGANSETT AVE,1120,DECEPTIVE PRACTICE,FORGERY,SIDEWALK,False,False,2511,25,36.0,19.0,10,1133202.0,1920006.0
7,066XX N MOZART ST,1242,DECEPTIVE PRACTICE,COMPUTER FRAUD,RESIDENCE,False,False,2412,24,50.0,2.0,11,1156129.0,1943876.0
8,038XX W THOMAS ST,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,1112,11,27.0,23.0,5,1150752.0,1907066.0
9,007XX N RIDGEWAY AV,820,THEFT,$500 AND UNDER,RESIDENCE PORCH/HALLWAY,False,True,1112,11,NaN,NaN,6,1151291.0,1904767.0
10,015XX W TAYLOR ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,1231,12,NaN,NaN,26,1166287.0,1895626.0
11,020XX W JARVIS AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,2424,24,NaN,NaN,7,1161511.0,1948737.0
12,001XX W MAPLE ST,1900,OTHER NARCOTIC VIOLATION,INTOXICATING COMPOUNDS,RESIDENCE,False,True,1824,18,27.0,8.0,18,1174883.0,1907592.0
13,026XX N CALIFORNIA AVE,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,RESIDENCE,False,False,1411,14,1.0,22.0,14,1157259.0,1917437.0
14,009XX W LAWRENCE AV,281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,STREET,False,False,2024,20,NaN,NaN,2,1168955.0,1932101.0
15,097XX S YATES AV,810,THEFT,OVER $500,RESIDENCE,False,False,431,4,NaN,NaN,6,1194154.0,1840505.0
16,030XX W GUNNISON ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1713,17,NaN,NaN,14,1154906.0,1932098.0
17,010XX W 104 PL,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,2232,22,NaN,NaN,7,1171423.0,1835564.0
18,002XX E 38TH ST,4650,OTHER OFFENSE,SEX OFFENDER - FAIL TO REGISTER,PARK PROPERTY,True,False,212,2,3.0,35.0,26,1178637.0,1879851.0
19,009XX W 31ST ST,1310,CRIMINAL DAMAGE,TO PROPERTY,STREET,False,False,913,9,11.0,60.0,14,1170183.0,1884289.0
20,080XX S KILBOURN AVE,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,834,8,18.0,70.0,17,NaN,NaN
21,066XX S MARYLAND AVE,1152,DECEPTIVE PRACTICE,ILLEGAL USE CASH CARD,RESIDENCE,False,False,321,3,20.0,42.0,11,1183034.0,1861240.0
22,043XX N RICHMOND ST,1753,OFFENSE INVOLVING CHILDREN,SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER,RESIDENCE,False,True,1724,17,33.0,16.0,2,NaN,NaN
23,015XX E 68 ST,820,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,332,3,NaN,NaN,6,1187807.0,1860170.0
24,072XX S WOLCOTT AV,820,THEFT,$500 AND UNDER,STREET,False,False,735,7,NaN,NaN,6,1164987.0,1856402.0
25,107XX S LA SALLE ST,810,THEFT,OVER $500,RESIDENCE-GARAGE,True,False,513,5,NaN,NaN,6,1177215.0,1833797.0
26,009XX N TRUMBULL AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1121,11,NaN,NaN,7,1153243.0,1906085.0
27,014XX N OAKLEY AV,610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,False,False,1424,14,NaN,NaN,5,1160841.0,1909871.0
28,024XX N SEMINARY AVE,810,THEFT,OVER $500,STREET,False,False,1932,19,43.0,7.0,6,1168559.0,1916293.0
29,002XX N HAMLIN BLVD,1310,CRIMINAL DAMAGE,TO PROPERTY,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,False,False,1122,11,28.0,26.0,14,1151029.0,1900696.0
30,001XX E 47TH ST,620,BURGLARY,UNLAWFUL ENTRY,GROCERY FOOD STORE,False,False,215,2,3.0,38.0,5,1178100.0,1873900.0
31,051XX W 64 PL,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,813,8,NaN,NaN,7,1142788.0,1861233.0
32,015XX E 83RD ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER (SPECIFY),False,False,412,4,8.0,45.0,11,NaN,NaN
33,064XX S EBERHART AV,810,THEFT,OVER $500,STREET,False,False,312,3,NaN,NaN,6,1180720.0,1862633.0
34,001XX E WALTON ST,810,THEFT,OVER $500,STREET,False,False,1833,18,NaN,NaN,6,1176987.0,1906980.0
35,010XX N SACRAMENTO AVE,560,ASSAULT,SIMPLE,SIDEWALK,False,False,1211,12,26.0,24.0,08A,1156188.0,1907011.0
36,021XX N DAMEN AV,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,1432,14,NaN,NaN,17,1162714.0,1914344.0
37,051XX N EAST RIVER RD,820,THEFT,$500 AND UNDER,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,1614,16,41.0,76.0,6,1116630.0,1933219.0
38,014XX N SEDGWICK ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1821,18,27.0,8.0,17,NaN,NaN
39,015XX S WABASH AVE,890,THEFT,FROM BUILDING,RESIDENCE,False,False,131,1,3.0,33.0,6,1177014.0,1892876.0
40,033XX W 84TH PL,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,False,False,834,8,18.0,70.0,11,1155676.0,1848366.0
41,001XX N PINE AV,820,THEFT,$500 AND UNDER,RESIDENCE,False,False,1523,15,NaN,NaN,6,1139523.0,1900383.0
42,028XX S KOMENSKY AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,SCHOOL - PUBLIC BUILDING,False,False,1031,10,22.0,30.0,17,NaN,NaN
43,012XX W NEWPORT AV,842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,1924,19,NaN,NaN,6,1167600.0,1923090.0
44,010XX S CANAL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,COMMERCIAL / BUSINESS OFFICE,False,False,124,1,28.0,28.0,11,NaN,NaN
45,013XX N WESTERN AV,810,THEFT,OVER $500,RESIDENCE PORCH/HALLWAY,False,False,1424,14,NaN,NaN,6,1160199.0,1909085.0
46,009XX N CENTRAL AVE,810,THEFT,OVER $500,RESIDENCE,False,False,1524,15,37.0,25.0,6,1138851.0,1905567.0
47,022XX N LAMON AV,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,2522,25,NaN,NaN,26,1143394.0,1914673.0
48,010XX N FRANCISCO AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,HOSPITAL BUILDING / GROUNDS,False,False,1211,12,26.0,24.0,11,1156861.0,1906972.0
49,027XX W HARRISON ST,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,True,1135,11,28.0,27.0,2,1158248.0,1897253.0
50,104XX S MICHIGAN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,512,5,9.0,49.0,11,1178871.0,1835534.0
51,019XX W 64TH ST,1120,DECEPTIVE PRACTICE,FORGERY,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,False,False,726,7,16.0,67.0,10,1164702.0,1862225.0
52,089XX S DAUPHIN AVE,502P,OTHER OFFENSE,FALSE / STOLEN / ALTERED TRP,STREET,False,False,633,6,8.0,44.0,26,1183792.0,1845732.0
53,036XX N NEWLAND AV,610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,False,False,1632,16,NaN,NaN,5,1129394.0,1923344.0
54,067XX N CLARK ST,910,MOTOR VEHICLE THEFT,AUTOMOBILE,VEHICLE NON-COMMERCIAL,False,False,2432,24,49.0,1.0,7,1163812.0,1944780.0
55,088XX S CARPENTER ST,920,MOTOR VEHICLE THEFT,ATTEMPT - AUTOMOBILE,STREET,False,False,2222,22,21.0,71.0,7,1170860.0,1846267.0
56,037XX S VINCENNES AVE,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,VEHICLE NON-COMMERCIAL,False,False,212,2,4.0,35.0,11,1180854.0,1880094.0
57,005XX N CENTRAL AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1523,15,37.0,25.0,14,1138937.0,1903092.0
58,0000X N KILBOURN AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,GAS STATION,False,False,1113,11,28.0,26.0,14,1146387.0,1899777.0
59,007XX N OGDEN AV,810,THEFT,OVER $500,STREET,False,False,1323,12,NaN,NaN,6,1168894.0,1905380.0

In [ ]:
#second max block having nan values 3 ,block='001XX N STATE ST'
#first 8 row,block 100XX W OHARE ST

In [5]:
null_count = crimes['Latitude'].isnull().sum() 
print(f'Number of null values in latitude column: {null_count}')

Number of null values in latitude column: 1477

In [6]:
crimes.to_csv('crime_just_1.csv', index=False)

In [2]:
import pandas as pd
cri=pd.read_csv(r"C:\Users\krebi\Downloads\crime_just.csv")
cri.head(5)

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
0,1410349,G129070,065XX S WESTERN AV,1310,CRIMINAL DAMAGE,TO PROPERTY,OTHER,False,False,832,...,14,1161535.0,1861313.0,2001,17-08-2015 15:03,41.775116,-87.683386,"(41.775116246, -87.683386215)",04-03-2001,00:00:00
1,12943357,JG105846,029XX S DR MARTIN LUTHER KING JR DR,890,THEFT,FROM BUILDING,APARTMENT,False,False,133,...,6,1179389.0,1885691.0,2022,15-11-2023 15:41,41.841623,-87.617191,"(41.841622651, -87.617191438)",19-12-2022,00:00:00
2,1387139,G100055,030XX W WABANSIA AV,820,THEFT,$500 AND UNDER,STREET,False,False,1421,...,6,1155995.0,1911189.0,2001,17-08-2015 15:03,41.912095,-87.702352,"(41.912094921, -87.70235198)",18-01-2001,00:00:00
3,13277780,JG504858,011XX W NEWPORT AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1924,...,17,NaN,NaN,2013,15-11-2023 15:42,NaN,NaN,NaN,01-06-2013,00:00:00
4,12893837,JF475901,024XX W 48TH ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,922,...,17,1160851.0,1872780.0,2022,05-02-2024 15:40,41.806597,-87.685577,"(41.806597377, -87.685576958)",09-11-2022,00:00:00

In [3]:
crime=pd.read_excel(r"C:\Users\krebi\Downloads\Crime_Data.xlsx")
crime.head(5)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,5741943,HN549294,2007-08-25 09:22:18,074XX N ROGERS AVE,560,ASSAULT,SIMPLE,OTHER,False,False,...,49.0,1.0,08A,NaN,NaN,2007,2015-08-17 15:03:40,NaN,NaN,NaN
1,25953,JE240540,2021-05-24 15:06:00,020XX N LARAMIE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,36.0,19.0,01A,1141387.0,1913179.0,2021,2023-11-18 15:39:49,41.917838,-87.755969,"(41.917838056, -87.755968972)"
2,26038,JE279849,2021-06-26 09:24:00,062XX N MC CORMICK RD,110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,50.0,13.0,01A,1152781.0,1941458.0,2021,2023-11-18 15:39:49,41.995219,-87.713355,"(41.995219444, -87.713354912)"
3,13279676,JG507211,2023-11-09 07:30:00,019XX W BYRON ST,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,47.0,5.0,5,1162518.0,1925906.0,2023,2023-11-18 15:39:49,41.952345,-87.677975,"(41.952345086, -87.677975059)"
4,13274752,JG501049,2023-11-12 07:59:00,086XX S COTTAGE GROVE AVE,454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",SMALL RETAIL STORE,True,False,...,6.0,44.0,08B,1183071.0,1847869.0,2023,2023-12-09 15:41:24,41.737751,-87.604856,"(41.737750767, -87.604855911)"

In [4]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549999 entries, 0 to 549998
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549999 non-null  int64
 1   Case Number           549999 non-null  object
 2   Date                  549999 non-null  datetime64[ns]
 3   Block                 549999 non-null  object
 4   IUCR                  549999 non-null  object
 5   Primary Type          549999 non-null  object
 6   Description           549999 non-null  object
 7   Location Description  548326 non-null  object
 8   Arrest                549999 non-null  bool
 9   Domestic              549999 non-null  bool
 10  Beat                  549999 non-null  int64
 11  District              549999 non-null  int64
 12  Ward                  213674 non-null  float64
 13  Community Area        215093 non-null  float64
 14  FBI Code              549999 non-null  object
 15  X Coordinate          543087 non-null  float64
 16  Y Coordinate          543087 non-null  float64
 17  Year                  549999 non-null  int64
 18  Updated On            549999 non-null  datetime64[ns]
 19  Latitude              543087 non-null  float64
 20  Longitude             543087 non-null  float64
 21  Location              543087 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 85.0+ MB

In [5]:

crime['Date'] = pd.to_datetime(crime['Date']) 
crime['Updated On'] = pd.to_datetime(crime['Updated On']) 
condition = crime['Date'] > crime['Updated On'] 
result = crime[condition] 
print(result)

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 22 columns]

In [6]:
# FILLING NAN VALUES IN CONTINUES DATA COLUMNS WITH BLOCKWISE MEDIAN
# First, handle blocks with sufficient data
cri[['Latitude', 'Longitude', 'X Coordinate', 'Y Coordinate']] = cri.groupby('Block')[
    ['Latitude', 'Longitude', 'X Coordinate', 'Y Coordinate']
].transform(lambda x: x.fillna(x.median()))

# Then, for blocks with all NaN values, you might want to:
# 1. Fill with the overall median of the entire dataset
remaining_nulls = cri[['Latitude', 'Longitude', 'X Coordinate', 'Y Coordinate']].isna()
for col in ['Latitude', 'Longitude', 'X Coordinate', 'Y Coordinate']:
    overall_median = cri[col].median()
    cri[col] = cri[col].fillna(overall_median)

In [41]:
null_count = cri['Location Description'].isnull().sum() 
print(f'Number of null values in latitude column: {null_count}')

Number of null values in latitude column: 0

In [30]:
display(cri.iloc[:60,10:16])
# a=cri.groupby("Community Area").count()
# display(a)
# b=cri.groupby("Location Description").count()
# display(b)

    District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate
0          8   NaN             NaN       14     1161535.0     1861313.0
1          1   4.0            35.0        6     1179389.0     1885691.0
2         14   NaN             NaN        6     1155995.0     1911189.0
3         19  44.0             6.0       17     1168096.0     1923064.0
4          9  15.0            58.0       17     1160851.0     1872780.0
5         11  28.0            26.0      08B     1150858.0     1900145.0
6         25  36.0            19.0       10     1133202.0     1920006.0
7         24  50.0             2.0       11     1156129.0     1943876.0
8         11  27.0            23.0        5     1150752.0     1907066.0
9         11   NaN             NaN        6     1151291.0     1904767.0
10        12   NaN             NaN       26     1166287.0     1895626.0
11        24   NaN             NaN        7     1161511.0     1948737.0
12        18  27.0             8.0       18     1174883.0     1907592.0
13        14   1.0            22.0       14     1157259.0     1917437.0
14        20   NaN             NaN        2     1168955.0     1932101.0
15         4   NaN             NaN        6     1194154.0     1840505.0
16        17   NaN             NaN       14     1154906.0     1932098.0
17        22   NaN             NaN        7     1171423.0     1835564.0
18         2   3.0            35.0       26     1178637.0     1879851.0
19         9  11.0            60.0       14     1170183.0     1884289.0
20         8  18.0            70.0       17     1147800.5     1850833.0
21         3  20.0            42.0       11     1183034.0     1861240.0
22        17  33.0            16.0        2     1155969.0     1928653.0
23         3   NaN             NaN        6     1187807.0     1860170.0
24         7   NaN             NaN        6     1164987.0     1856402.0
25         5   NaN             NaN        6     1177215.0     1833797.0
26        11   NaN             NaN        7     1153243.0     1906085.0
27        14   NaN             NaN        5     1160841.0     1909871.0
28        19  43.0             7.0        6     1168559.0     1916293.0
29        11  28.0            26.0       14     1151029.0     1900696.0
30         2   3.0            38.0        5     1178100.0     1873900.0
31         8   NaN             NaN        7     1142788.0     1861233.0
32         4   8.0            45.0       11     1188061.0     1850257.0
33         3   NaN             NaN        6     1180720.0     1862633.0
34        18   NaN             NaN        6     1176987.0     1906980.0
35        12  26.0            24.0      08A     1156188.0     1907011.0
36        14   NaN             NaN       17     1162714.0     1914344.0
37        16  41.0            76.0        6     1116630.0     1933219.0
38        18  27.0             8.0       17     1173383.0     1909988.0
39         1   3.0            33.0        6     1177014.0     1892876.0
40         8  18.0            70.0       11     1155676.0     1848366.0
41        15   NaN             NaN        6     1139523.0     1900383.0
42        10  22.0            30.0       17     1149839.0     1884853.0
43        19   NaN             NaN        6     1167600.0     1923090.0
44         1  28.0            28.0       11     1173291.0     1895810.0
45        14   NaN             NaN        6     1160199.0     1909085.0
46        15  37.0            25.0        6     1138851.0     1905567.0
47        25   NaN             NaN       26     1143394.0     1914673.0
48        12  26.0            24.0       11     1156861.0     1906972.0
49        11  28.0            27.0        2     1158248.0     1897253.0
50         5   9.0            49.0       11     1178871.0     1835534.0
51         7  16.0            67.0       10     1164702.0     1862225.0
52         6   8.0            44.0       26     1183792.0     1845732.0
53        16   NaN             NaN        5     1129394.0     1923344.0
54        24  49.0             1.0        7     1163812.0     1944780.0
55        22  21.0            71.0        7     1170860.0     1846267.0
56         2   4.0            35.0       11     1180854.0     1880094.0
57        15  37.0            25.0       14     1138937.0     1903092.0
58        11  28.0            26.0       14     1146387.0     1899777.0
59        12   NaN             NaN        6     1168894.0     1905380.0

In [68]:
#CHECKING BLOCKWISE NULL VALUES IN LOCATION DESCRIPTION BY CHNAGING nlargest
block_counts = cri.groupby('Location Description')['Location Description'].count()
second_max_block_count = block_counts.nlargest(21).iloc[-1]
print(f"The second largest block count is: {second_max_block_count}")

# Find the blocks with the second largest count
second_max_blocks = block_counts[block_counts == second_max_block_count].index
second_max_block_rows = cri[cri['Location Description'].isin(second_max_blocks)]

display(cri[cri['Location Description'].isin(second_max_blocks)])
nan_latitude_rows = second_max_block_rows[second_max_block_rows['Location Description'].isna()]
display(nan_latitude_rows)

The second largest block count is: 3993

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
18,12511112,JE408461,002XX E 38TH ST,4650,OTHER OFFENSE,SEX OFFENDER - FAIL TO REGISTER,PARK PROPERTY,True,False,212,...,26,1178637.0,1879851.0,2021,19-12-2023 15:46,41.825614,-87.620129,"(41.825614426, -87.620128934)",13-10-2021,00:00:00
376,1808821,G638013,039XX N LAKE SHORE DR,810,THEFT,OVER $500,PARK PROPERTY,False,False,2323,...,6,1171483.0,1926611.0,2001,17-08-2015 15:03,41.954087,-87.644999,"(41.954086783, -87.644998878)",23-10-2001,00:00:00
466,13359429,JH141308,026XX W 105TH ST,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,PARK PROPERTY,False,False,2211,...,14,1160691.0,1834912.0,2024,12-02-2024 15:40,41.702685,-87.687207,"(41.702685181, -87.687206859)",05-02-2024,00:00:00
527,1422001,G142420,107XX S SAWYER AV,1310,CRIMINAL DAMAGE,TO PROPERTY,PARK PROPERTY,False,False,2211,...,14,1156626.0,1833345.0,2001,17-08-2015 15:03,41.698468,-87.702134,"(41.698467771, -87.702134052)",09-03-2001,00:00:00
1090,1686746,G473560,051XX N FRANCISCO AV,1310,CRIMINAL DAMAGE,TO PROPERTY,PARK PROPERTY,False,False,2031,...,14,1156074.0,1933774.0,2001,17-08-2015 15:03,41.974068,-87.701450,"(41.974068114, -87.701450123)",08-08-2001,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547940,13251462,JG473243,059XX N BROADWAY,486,BATTERY,DOMESTIC BATTERY SIMPLE,PARK PROPERTY,False,True,2022,...,08B,1167232.0,1939500.0,2023,29-10-2023 15:42,41.989547,-87.660254,"(41.989547243, -87.660253739)",21-10-2023,23:52:00
548008,1531472,G281012,006XX E SOLIDARITY DR,460,BATTERY,SIMPLE,PARK PROPERTY,False,False,133,...,08B,1180581.0,1894781.0,2001,17-08-2015 15:03,41.866539,-87.612537,"(41.866538806, -87.612537229)",15-05-2001,23:52:11
548128,13273454,JG499663,043XX S CALUMET AVE,560,ASSAULT,SIMPLE,PARK PROPERTY,False,True,215,...,08A,1179159.0,1876234.0,2023,18-11-2023 15:40,41.815677,-87.618324,"(41.815677181, -87.618324289)",10-11-2023,23:53:00
548184,1588782,G348869,031XX N LAKE SHORE DR,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,PARK PROPERTY,True,False,2332,...,22,1173642.0,1920750.0,2001,17-08-2015 15:03,41.937956,-87.637237,"(41.937956157, -87.637237174)",15-06-2001,23:53:43
548945,13429503,JH225463,065XX S PROMONTORY DR,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,PARK PROPERTY,True,False,331,...,15,1192337.0,1862034.0,2024,22-04-2024 15:41,41.776400,-87.570448,"(41.776400433, -87.570448042)",14-04-2024,23:57:00

Empty DataFrame
Columns: [ID, Case Number, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location, DATE, TIME]
Index: []

[0 rows x 23 columns]

In [32]:
filtered_crime = cri[
    (cri['Community Area'] == 35.0) & (~cri['Community Area'].isna())
]

# Display the first 5 rows
display(filtered_crime.iloc[:60,10:16])

      District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate
1            1   4.0            35.0        6     1179389.0     1885691.0
18           2   3.0            35.0       26     1178637.0     1879851.0
56           2   4.0            35.0       11     1180854.0     1880094.0
110          1   3.0            35.0       11     1176158.0     1885352.0
189          1   4.0            35.0        7     1178035.0     1886949.0
191          1   4.0            35.0        6     1179394.0     1885524.0
365          1   4.0            35.0      04A     1178044.0     1886556.0
550          1   3.0            35.0       26     1177205.0     1885463.0
612          2   4.0            35.0       10     1181095.0     1882300.0
754          1   4.0            35.0      08B     1177726.0     1885751.0
892          1   4.0            35.0        6     1179394.0     1885524.0
983          2   3.0            35.0       11     1178842.0     1881615.0
1107         2   4.0            35.0       14     1181288.0     1882381.0
1165         1   4.0            35.0       14     1179263.0     1886551.0
1331         1   4.0            35.0        6     1179378.0     1886082.0
1878         2   3.0            35.0      04B     1179336.0     1879867.0
2000         1   4.0            35.0        7     1178484.0     1887040.0
2108         1   4.0            35.0        2     1178033.0     1887015.0
2222         1   3.0            35.0       17     1176316.0     1886554.0
2327         2   4.0            35.0      08A     1180162.0     1881716.0
2450         2   3.0            35.0       11     1176805.0     1880472.0
2511         2   3.0            35.0       26     1177772.0     1881665.0
2689         1   3.0            35.0       11     1176743.0     1886065.0
2782         2   3.0            35.0        7     1177142.0     1880973.0
2817         2   4.0            35.0       17     1180162.0     1881716.0
2922         1   4.0            35.0      08B     1179389.0     1885691.0
2928         1   3.0            35.0       26     1176459.0     1885004.0
3023         1   3.0            35.0      04A     1176241.0     1885750.0
3410         2   3.0            35.0       11     1178214.0     1880299.0
3636         2   4.0            35.0       14     1179100.0     1881440.0
3701         2   4.0            35.0       11     1179406.0     1881825.0
3717         2   3.0            35.0        6     1179487.0     1879584.0
3736         1   3.0            35.0        6     1177636.0     1886562.0
3763         2   3.0            35.0       11     1176851.0     1880900.0
3805         2   4.0            35.0       14     1180911.0     1883686.0
3852         2   4.0            35.0       14     1180161.0     1881775.0
3936         2   4.0            35.0        6     1179157.0     1882306.0
4056         2   3.0            35.0       26     1178466.0     1883513.0
4339         2   3.0            35.0       26     1178163.0     1882297.0
4424         1   4.0            35.0        5     1179408.0     1885031.0
4427         1   4.0            35.0        7     1179378.0     1886082.0
4514         2   4.0            35.0       14     1179099.0     1881470.0
4522         2   4.0            35.0      08B     1181129.0     1882697.0
4711         1   3.0            35.0       11     1177041.0     1887123.0
4852         2   3.0            35.0       14     1177786.0     1881145.0
4941         1   4.0            35.0        6     1178033.0     1887015.0
4960         2   3.0            35.0       11     1177492.0     1880157.0
5087         2   4.0            35.0        6     1178829.0     1882214.0
5356         2   4.0            35.0      08B     1180729.0     1879459.0
5364         1   4.0            35.0        6     1179408.0     1885031.0
5394         2   4.0            35.0      08A     1180708.0     1882808.0
5452         2   4.0            35.0       11     1180360.0     1883173.0
5550         2   4.0            35.0       11     1179324.0     1884357.0
5570         1   4.0            35.0       14     1179263.0     1886551.0
5968         2   4.0            35.0        7     1179468.0     1881552.0
6025         2   3.0            35.0       14     1177828.0     1879596.0
6039         2   4.0            35.0        6     1180539.0     1883677.0
6130         2   4.0            35.0        7     1180539.0     1883677.0
6135         1   3.0            35.0       11     1176758.0     1885480.0
6201         2   3.0            35.0       11     1178152.0     1882839.0

In [46]:
grouped = cri.groupby(['Block', 'Community Area','Ward']) # Aggregating data (e.g., count of cases) 
grouped_count = grouped.size().reset_index(name='Case Count')
display(grouped_count)

                     Block  Community Area  Ward  Case Count
0         0000X E 100TH PL            49.0   9.0           7
1         0000X E 100TH ST            49.0   9.0          10
2         0000X E 101ST PL            49.0   9.0          13
3         0000X E 101ST ST            49.0   9.0           7
4         0000X E 102ND PL            49.0   9.0           4
...                    ...             ...   ...         ...
32831   137XX S DOTY AVE W            54.0   9.0           1
32832   137XX S DOTY AVE W            54.0  10.0           1
32833  137XX S INDIANA AVE            54.0   9.0           4
32834   137XX S LEYDEN AVE            54.0   9.0           1
32835   137XX S LEYDEN AVE            54.0  10.0           3

[32836 rows x 4 columns]

In [43]:
# Count unique 'Community Area' values per 'Block'
block_community_counts = cri.groupby('Block')['Community Area'].nunique().reset_index()

# Rename the columns for clarity
block_community_counts.columns = ['Block', 'Unique Community Area Count']

# Display the result
display(block_community_counts)

                     Block  Unique Community Area Count
0           0000X E 100 PL                            1
1           0000X E 100 ST                            1
2         0000X E 100TH PL                            1
3         0000X E 100TH ST                            1
4           0000X E 101 PL                            1
...                    ...                          ...
51014   137XX S INDIANA AV                            1
51015  137XX S INDIANA AVE                            1
51016   137XX S JEFFERY AV                            1
51017    137XX S LEYDEN AV                            1
51018   137XX S LEYDEN AVE                            1

[51019 rows x 2 columns]

In [36]:
# Count unique 'Community Area', including NaN
block_community_counts = cri.groupby('Block')['Community Area'].nunique(dropna=False).reset_index()
block_community_counts.columns = ['Block', 'Unique Community Area Count (Including NaN)']

# Display the result
display(block_community_counts)

                     Block  Unique Community Area Count (Including NaN)
0           0000X E 100 PL                                            1
1           0000X E 100 ST                                            1
2         0000X E 100TH PL                                            1
3         0000X E 100TH ST                                            1
4           0000X E 101 PL                                            1
...                    ...                                          ...
51014   137XX S INDIANA AV                                            1
51015  137XX S INDIANA AVE                                            1
51016   137XX S JEFFERY AV                                            1
51017    137XX S LEYDEN AV                                            1
51018   137XX S LEYDEN AVE                                            1

[51019 rows x 2 columns]

In [38]:
# Fill NaN 'Community Area' based on median of each Block
cri['Community Area'] = cri['Community Area'].fillna(
    cri.groupby('Block')['Community Area'].transform('median')
)

In [39]:
# Fill remaining NaN with global median
global_median = cri['Community Area'].median()
cri['Community Area'] = cri['Community Area'].fillna(global_median)

In [40]:
# Recalculate unique counts
block_community_counts = cri.groupby('Block')['Community Area'].nunique().reset_index()
block_community_counts.columns = ['Block', 'Unique Community Area Count']

# Check if any blocks still have 0 unique count
print("Blocks with 0 unique Community Area count:", 
      block_community_counts[block_community_counts['Unique Community Area Count'] == 0].shape[0])

Blocks with 0 unique Community Area count: 0

In [44]:
cri.head(50)

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,DATE,TIME
0,1410349,G129070,065XX S WESTERN AV,1310,CRIMINAL DAMAGE,TO PROPERTY,OTHER,False,False,832,...,14,1161535.0,1861313.0,2001,17-08-2015 15:03,41.775116,-87.683386,"(41.775116246, -87.683386215)",04-03-2001,00:00:00
1,12943357,JG105846,029XX S DR MARTIN LUTHER KING JR DR,890,THEFT,FROM BUILDING,APARTMENT,False,False,133,...,6,1179389.0,1885691.0,2022,15-11-2023 15:41,41.841623,-87.617191,"(41.841622651, -87.617191438)",19-12-2022,00:00:00
2,1387139,G100055,030XX W WABANSIA AV,820,THEFT,$500 AND UNDER,STREET,False,False,1421,...,6,1155995.0,1911189.0,2001,17-08-2015 15:03,41.912095,-87.702352,"(41.912094921, -87.70235198)",18-01-2001,00:00:00
3,13277780,JG504858,011XX W NEWPORT AVE,1751,OFFENSE INVOLVING CHILDREN,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1924,...,17,1168096.0,1923064.0,2013,15-11-2023 15:42,41.944428,-87.657553,NaN,01-06-2013,00:00:00
4,12893837,JF475901,024XX W 48TH ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,922,...,17,1160851.0,1872780.0,2022,05-02-2024 15:40,41.806597,-87.685577,"(41.806597377, -87.685576958)",09-11-2022,00:00:00
5,13455562,JH257457,038XX W WASHINGTON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,1122,...,08B,1150858.0,1900145.0,2024,17-05-2024 15:41,41.881891,-87.721513,"(41.881891223, -87.721513301)",10-05-2024,00:00:00
6,13220222,JG435844,031XX N NARRAGANSETT AVE,1120,DECEPTIVE PRACTICE,FORGERY,SIDEWALK,False,False,2511,...,10,1133202.0,1920006.0,2023,25-09-2023 15:42,41.936719,-87.785881,"(41.93671942, -87.785881395)",18-09-2023,00:00:00
7,13215685,JG430483,066XX N MOZART ST,1242,DECEPTIVE PRACTICE,COMPUTER FRAUD,RESIDENCE,False,False,2412,...,11,1156129.0,1943876.0,2023,25-09-2023 15:42,42.001787,-87.700974,"(42.001787361, -87.700973587)",18-09-2023,00:00:00
8,13405860,JH196942,038XX W THOMAS ST,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,1112,...,5,1150752.0,1907066.0,2024,28-03-2024 15:42,41.900885,-87.721721,"(41.900885238, -87.721721384)",21-03-2024,00:00:00
9,1621435,G389801,007XX N RIDGEWAY AV,820,THEFT,$500 AND UNDER,RESIDENCE PORCH/HALLWAY,False,True,1112,...,6,1151291.0,1904767.0,2001,07-09-2021 15:41,41.894566,-87.719802,"(41.894565991, -87.719801973)",03-07-2001,00:00:00
10,1445199,G173688,015XX W TAYLOR ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,1231,...,26,1166287.0,1895626.0,2001,17-08-2015 15:03,41.869175,-87.664987,"(41.869174911, -87.664987504)",26-03-2001,00:00:00
11,1408047,G125403,020XX W JARVIS AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,2424,...,7,1161511.0,1948737.0,2001,17-08-2015 15:03,42.015015,-87.681038,"(42.015015291, -87.681037643)",03-03-2001,00:00:00
12,12949823,JG113247,001XX W MAPLE ST,1900,OTHER NARCOTIC VIOLATION,INTOXICATING COMPOUNDS,RESIDENCE,False,True,1824,...,18,1174883.0,1907592.0,2022,15-11-2023 15:41,41.901822,-87.633071,"(41.901822321, -87.633071176)",23-12-2022,00:00:00
13,13261898,JG485858,026XX N CALIFORNIA AVE,1305,CRIMINAL DAMAGE,CRIMINAL DEFACEMENT,RESIDENCE,False,False,1411,...,14,1157259.0,1917437.0,2023,03-11-2023 15:41,41.929214,-87.697538,"(41.929214304, -87.697538213)",27-10-2023,00:00:00
14,1650698,G431595,009XX W LAWRENCE AV,281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,STREET,False,False,2024,...,2,1168955.0,1932101.0,2001,17-08-2015 15:03,41.969207,-87.654132,"(41.969206868, -87.65413209)",23-07-2001,00:00:00
15,1690936,G482957,097XX S YATES AV,810,THEFT,OVER $500,RESIDENCE,False,False,431,...,6,1194154.0,1840505.0,2001,17-08-2015 15:03,41.717279,-87.564492,"(41.717278669, -87.564492358)",31-07-2001,00:00:00
16,1563311,G324472,030XX W GUNNISON ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1713,...,14,1154906.0,1932098.0,2001,17-08-2015 15:03,41.969493,-87.705790,"(41.969492635, -87.705790342)",05-06-2001,00:00:00
17,1587424,G356160,010XX W 104 PL,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,2232,...,7,1171423.0,1835564.0,2001,17-08-2015 15:03,41.704247,-87.647890,"(41.704246697, -87.647889932)",19-06-2001,00:00:00
18,12511112,JE408461,002XX E 38TH ST,4650,OTHER OFFENSE,SEX OFFENDER - FAIL TO REGISTER,PARK PROPERTY,True,False,212,...,26,1178637.0,1879851.0,2021,19-12-2023 15:46,41.825614,-87.620129,"(41.825614426, -87.620128934)",13-10-2021,00:00:00
19,13402169,JH192706,009XX W 31ST ST,1310,CRIMINAL DAMAGE,TO PROPERTY,STREET,False,False,913,...,14,1170183.0,1884289.0,2024,21-03-2024 15:47,41.837981,-87.651015,"(41.837981108, -87.651015101)",14-03-2024,00:00:00
20,12938408,JG100185,080XX S KILBOURN AVE,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,False,True,834,...,17,1147800.5,1850833.0,2020,19-12-2023 15:46,41.746631,-87.734003,NaN,01-11-2020,00:00:00
21,13377793,JH163056,066XX S MARYLAND AVE,1152,DECEPTIVE PRACTICE,ILLEGAL USE CASH CARD,RESIDENCE,False,False,321,...,11,1183034.0,1861240.0,2024,28-02-2024 15:41,41.774443,-87.604576,"(41.774443027, -87.604576499)",21-02-2024,00:00:00
22,11260706,JB191450,043XX N RICHMOND ST,1753,OFFENSE INVOLVING CHILDREN,SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER,RESIDENCE,False,True,1724,...,2,1155969.0,1928653.0,2015,05-02-2024 15:40,41.960019,-87.701970,NaN,19-03-2015,00:00:00
23,1630730,G411490,015XX E 68 ST,820,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,332,...,6,1187807.0,1860170.0,2001,17-08-2015 15:03,41.771395,-87.587114,"(41.771394537, -87.587113776)",14-07-2001,00:00:00
24,1521954,G269638,072XX S WOLCOTT AV,820,THEFT,$500 AND UNDER,STREET,False,False,735,...,6,1164987.0,1856402.0,2001,17-08-2015 15:03,41.761568,-87.670870,"(41.761567508, -87.670870257)",10-05-2001,00:00:00
25,1655117,G440691,107XX S LA SALLE ST,810,THEFT,OVER $500,RESIDENCE-GARAGE,True,False,513,...,6,1177215.0,1833797.0,2001,17-08-2015 15:03,41.699269,-87.626734,"(41.699269334, -87.626733755)",19-07-2001,00:00:00
26,1645023,G431141,009XX N TRUMBULL AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1121,...,7,1153243.0,1906085.0,2001,17-08-2015 15:03,41.898144,-87.712598,"(41.898144184, -87.712597778)",22-07-2001,00:00:00
27,1609088,G384276,014XX N OAKLEY AV,610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,False,False,1424,...,5,1160841.0,1909871.0,2001,17-08-2015 15:03,41.908379,-87.684586,"(41.908379022, -87.684585761)",01-07-2001,00:00:00
28,13373480,JH157984,024XX N SEMINARY AVE,810,THEFT,OVER $500,STREET,False,False,1932,...,6,1168559.0,1916293.0,2024,25-02-2024 15:41,41.925838,-87.656047,"(41.92583767, -87.656047481)",18-02-2024,00:00:00
29,13456795,JH259032,002XX N HAMLIN BLVD,1310,CRIMINAL DAMAGE,TO PROPERTY,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,False,False,1122,...,14,1151029.0,1900696.0,2024,17-05-2024 15:41,41.883400,-87.720871,"(41.883399879, -87.720870948)",10-05-2024,00:00:00
30,13257659,JG480414,001XX E 47TH ST,620,BURGLARY,UNLAWFUL ENTRY,GROCERY FOOD STORE,False,False,215,...,5,1178100.0,1873900.0,2023,03-11-2023 15:41,41.809297,-87.622280,"(41.809296597, -87.622279702)",27-10-2023,00:00:00
31,1804849,G633282,051XX W 64 PL,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,813,...,7,1142788.0,1861233.0,2001,17-08-2015 15:03,41.775265,-87.752113,"(41.775264956, -87.752113236)",21-10-2001,00:00:00
32,12960182,JG125386,015XX E 83RD ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER (SPECIFY),False,False,412,...,11,1188061.0,1850257.0,2022,23-01-2023 15:42,41.744186,-87.586498,NaN,08-09-2022,00:00:00
33,1633028,G397657,064XX S EBERHART AV,810,THEFT,OVER $500,STREET,False,False,312,...,6,1180720.0,1862633.0,2001,17-08-2015 15:03,41.778319,-87.613016,"(41.778319052, -87.613016371)",04-05-2001,00:00:00
34,1473458,G200261,001XX E WALTON ST,810,THEFT,OVER $500,STREET,False,False,1833,...,6,1176987.0,1906980.0,2001,17-08-2015 15:03,41.900096,-87.625362,"(41.900095576, -87.625361561)",07-04-2001,00:00:00
35,13475905,JH282788,010XX N SACRAMENTO AVE,560,ASSAULT,SIMPLE,SIDEWALK,False,False,1211,...,08A,1156188.0,1907011.0,2024,03-06-2024 15:42,41.900626,-87.701756,"(41.900626231, -87.701755961)",27-05-2024,00:00:00
36,1425151,G144512,021XX N DAMEN AV,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,True,False,1432,...,17,1162714.0,1914344.0,2001,17-08-2015 15:03,41.920614,-87.677580,"(41.920614166, -87.677579664)",01-03-2001,00:00:00
37,12938619,JG100303,051XX N EAST RIVER RD,820,THEFT,$500 AND UNDER,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,1614,...,6,1116630.0,1933219.0,2022,15-11-2023 15:41,41.973252,-87.846511,"(41.973251862, -87.846511321)",29-12-2022,00:00:00
38,12958740,JG123507,014XX N SEDGWICK ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,1821,...,17,1173383.0,1909988.0,2019,21-01-2023 15:42,41.908431,-87.638510,NaN,01-05-2019,00:00:00
39,13358057,JH139510,015XX S WABASH AVE,890,THEFT,FROM BUILDING,RESIDENCE,False,False,131,...,6,1177014.0,1892876.0,2024,19-02-2024 15:40,41.861393,-87.625690,"(41.861392804, -87.62568954)",04-02-2024,00:00:00
40,12943368,JG105838,033XX W 84TH PL,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,False,False,834,...,11,1155676.0,1848366.0,2022,15-11-2023 15:41,41.739707,-87.705211,"(41.739707119, -87.70521125)",14-11-2022,00:00:00
41,1726188,G532061,001XX N PINE AV,820,THEFT,$500 AND UNDER,RESIDENCE,False,False,1523,...,6,1139523.0,1900383.0,2001,17-08-2015 15:03,41.882759,-87.763130,"(41.882758529, -87.763129964)",05-09-2001,00:00:00
42,13462575,JH264366,028XX S KOMENSKY AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,SCHOOL - PUBLIC BUILDING,False,False,1031,...,17,1149839.0,1884853.0,2017,17-05-2024 15:41,41.839948,-87.725652,NaN,01-01-2017,00:00:00
43,1542765,G293677,012XX W NEWPORT AV,842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,1924,...,6,1167600.0,1923090.0,2001,17-08-2015 15:03,41.944510,-87.659375,"(41.944509704, -87.659374971)",29-01-2001,00:00:00
44,13404925,JH195904,010XX S CANAL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,COMMERCIAL / BUSINESS OFFICE,False,False,124,...,11,1173291.0,1895810.0,2019,21-03-2024 15:47,41.869527,-87.639269,NaN,01-04-2019,00:00:00
45,1607805,G381471,013XX N WESTERN AV,810,THEFT,OVER $500,RESIDENCE PORCH/HALLWAY,False,False,1424,...,6,1160199.0,1909085.0,2001,17-08-2015 15:03,41.906235,-87.686966,"(41.906235477, -87.686965907)",30-06-2001,00:00:00
46,13269878,JG495814,009XX N CENTRAL AVE,810,THEFT,OVER $500,RESIDENCE,False,False,1524,...,6,1138851.0,1905567.0,2023,15-11-2023 15:42,41.896996,-87.765472,"(41.896996305, -87.76547163)",08-11-2023,00:00:00
47,1605264,G378363,022XX N LAMON AV,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,2522,...,26,1143394.0,1914673.0,2001,17-08-2015 15:03,41.921900,-87.748558,"(41.921900432, -87.748557643)",29-06-2001,00:00:00
48,13267721,JG493338,010XX N FRANCISCO AVE,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,HOSPITAL BUILDING / GROUNDS,False,False,1211,...,11,1156861.0,1906972.0,2023,16-11-2023 15:40,41.900506,-87.699285,"(41.900505589, -87.699285044)",01-09-2023,00:00:00
49,13261117,JG484836,027XX W HARRISON ST,281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,True,1135,...,2,1158248.0,1897253.0,2023,03-11-2023 15:41,41.873808,-87.694456,"(41.873807522, -87.69445629)",27-10-2023,00:00:00

In [45]:
cri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549434 entries, 0 to 549433
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549434 non-null  int64
 1   Case Number           549434 non-null  object
 2   Block                 549434 non-null  object
 3   IUCR                  549434 non-null  object
 4   Primary Type          549434 non-null  object
 5   Description           549434 non-null  object
 6   Location Description  547761 non-null  object
 7   Arrest                549434 non-null  bool
 8   Domestic              549434 non-null  bool
 9   Beat                  549434 non-null  int64
 10  District              549434 non-null  int64
 11  Ward                  213123 non-null  float64
 12  Community Area        549434 non-null  float64
 13  FBI Code              549434 non-null  object
 14  X Coordinate          549434 non-null  float64
 15  Y Coordinate          549434 non-null  float64
 16  Year                  549434 non-null  int64
 17  Updated On            549434 non-null  object
 18  Latitude              549434 non-null  float64
 19  Longitude             549434 non-null  float64
 20  Location              542522 non-null  object
 21  DATE                  549434 non-null  object
 22  TIME                  549434 non-null  object
dtypes: bool(2), float64(6), int64(4), object(11)
memory usage: 89.1+ MB

In [51]:
a=cri.groupby(['Community Area','Ward']).size().reset_index(name='Count')
display(a)

     Community Area  Ward  Count
0               1.0  40.0     73
1               1.0  49.0   3974
2               2.0  40.0    938
3               2.0  49.0    136
4               2.0  50.0   2202
..              ...   ...    ...
282            76.0  38.0     36
283            76.0  41.0   1365
284            77.0  40.0    462
285            77.0  48.0   2310
286            77.0  49.0      1

[287 rows x 3 columns]

In [52]:
# Group by 'Community Area' and count the number of unique 'Ward' values
community_area_ward_counts = cri.groupby('Community Area')['Ward'].nunique().reset_index()

# Rename the column for clarity
community_area_ward_counts.columns = ['Community Area', 'Ward Count']

# Display the result
display(community_area_ward_counts)

    Community Area  Ward Count
0              1.0           2
1              2.0           3
2              3.0           4
3              4.0           3
4              4.5           0
..             ...         ...
81            73.0           5
82            74.0           1
83            75.0           3
84            76.0           3
85            77.0           3

[86 rows x 2 columns]

In [54]:
# Step 1: Fill NaN values by Grouping by 'Community Area' and filling with Mode
def fill_with_mode(group):
    # Check if mode() returns a valid value
    mode_value = group.mode()
    if not mode_value.empty:
        return group.fillna(mode_value[0])  
    else:
        return group  

# Apply the function to fill NaN values within each group
cri['Ward'] = cri.groupby('Community Area')['Ward'].transform(fill_with_mode)

# Step 2: For any remaining NaN values, fill them with the Mode of the entire dataset
cri['Ward'].fillna(cri['Ward'].mode()[0], inplace=True)

C:\Users\krebi\AppData\Local\Temp\ipykernel_11752\915694343.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cri['Ward'].fillna(cri['Ward'].mode()[0], inplace=True)

In [52]:
a=cri.groupby('Location Description').value_counts()
display(a.tail(50))

Location Description  ID     Case Number  Block                    IUCR  Primary Type  Description          Arrest  Domestic  Beat  District  Ward  Community Area  FBI Code  X Coordinate  Y Coordinate  Year  Updated On        Latitude   Longitude   Location                       DATE        TIME
YARD                  26670  JF185299     040XX W MONROE ST        110   HOMICIDE      FIRST DEGREE MURDER  True    False     1115  11        28    26.0            01A       1149437.0     1899354.0     2022  19-09-2022 15:41  41.879748  -87.726752  (41.879748311, -87.726751761)  24-03-2022  16:53:00    1
                      26696  JF201938     015XX E 61ST ST          110   HOMICIDE      FIRST DEGREE MURDER  True    True      314   3         5     42.0            01A       1187664.0     1864701.0     2022  10-02-2024 15:40  41.783831  -87.587494  (41.783831376, -87.587493905)  08-04-2022  20:22:00    1
                      26748  JF233614     116XX S LOWE AVE         110   HOMICIDE      FIRST DEGREE MURDER  False   False     524   5         34    53.0            01A       1174024.0     1828074.0     2022  19-09-2022 15:41  41.683636  -87.638587  (41.683635787, -87.63858674)   07-05-2022  15:00:00    1
                      26779  JF251130     078XX S LAFLIN ST        110   HOMICIDE      FIRST DEGREE MURDER  True    False     612   6         17    71.0            01A       1167473.0     1852841.0     2022  19-09-2022 15:41  41.751743  -87.661861  (41.751742742, -87.661860682)  22-05-2022  01:31:00    1
                      26799  JF262294     078XX S COLFAX AVE       110   HOMICIDE      FIRST DEGREE MURDER  False   True      421   4         7     43.0            01A       1194880.0     1853485.0     2022  19-09-2022 15:41  41.752879  -87.561407  (41.752879083, -87.561406996)  31-05-2022  12:54:00    1
                      26826  JF275876     086XX S DAMEN AVE        110   HOMICIDE      FIRST DEGREE MURDER  True    False     614   6         18    71.0            01A       1164525.0     1847387.0     2022  03-06-2023 15:40  41.736839  -87.672817  (41.736838785, -87.67281718)   11-06-2022  15:21:00    1
                      26885  JF303652     007XX N SPRINGFIELD AVE  110   HOMICIDE      FIRST DEGREE MURDER  False   False     1112  11        37    23.0            01A       1150257.0     1904640.0     2022  19-09-2022 15:41  41.894238  -87.723603  (41.894237717, -87.723602898)  03-07-2022  10:22:00    1
                      26919  JF325913     079XX S LANGLEY AVE      110   HOMICIDE      FIRST DEGREE MURDER  True    False     624   6         6     44.0            01A       1182273.0     1852484.0     2022  04-03-2023 15:40  41.750433  -87.607637  (41.750433336, -87.607636954)  21-07-2022  11:56:00    1
                      26936  JF332884     001XX N LA CROSSE AVE    110   HOMICIDE      FIRST DEGREE MURDER  False   False     1532  15        28    25.0            01A       1144016.0     1900760.0     2022  19-09-2022 15:41  41.883710  -87.746622  (41.883709958, -87.746621843)  26-07-2022  21:44:00    1
                      26940  JF333745     112XX S EGGLESTON AVE    110   HOMICIDE      FIRST DEGREE MURDER  False   False     2233  22        34    49.0            01A       1175297.0     1830410.0     2022  01-09-2022 15:42  41.690018  -87.633857  (41.690017865, -87.633857295)  27-07-2022  15:15:00    1
                      26941  JF334293     040XX W WILCOX ST        110   HOMICIDE      FIRST DEGREE MURDER  False   False     1115  11        28    26.0            01A       1149468.0     1899030.0     2022  19-09-2022 15:41  41.878859  -87.726646  (41.878858618, -87.726646342)  28-07-2022  01:53:00    1
                      26953  JF343160     039XX W GLADYS AVE       110   HOMICIDE      FIRST DEGREE MURDER  True    False     1132  11        28    26.0            01A       1150234.0     1898066.0     2022  11-11-2022 15:40  41.876198  -87.723859  (41.876198401, -87.723858849)  03-08-2022  19:03:00    1
                      26961  JF346676     026XX S TRIPP AVE        110   HOMICIDE      FIRST DEGREE MURDER  False   False     1031  10        22    30.0            01A       1148483.0     1886023.0     2022  19-09-2022 15:41  41.843185  -87.730598  (41.843184863, -87.730598396)  06-08-2022  14:25:00    1
                      26984  JF352153     118XX S NORMAL AVE       110   HOMICIDE      FIRST DEGREE MURDER  True    False     522   5         34    53.0            01A       1175098.0     1826358.0     2022  28-11-2022 15:40  41.678903  -87.634706  (41.67890298, -87.634706134)   10-08-2022  21:13:00    1
                      27047  JF391862     124XX S HARVARD AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     523   5         34    53.0            01A       1176211.0     1822400.0     2022  19-09-2022 15:41  41.668017  -87.630750  (41.668016765, -87.630750254)  11-09-2022  13:01:00    1
                      27064  JF400540     007XX E 133RD ST         110   HOMICIDE      FIRST DEGREE MURDER  True    False     533   5         9     54.0            01A       1183678.0     1817496.0     2022  02-02-2023 15:41  41.654389  -87.603575  (41.654389164, -87.60357486)   18-09-2022  07:33:00    1
                      27072  JF407807     063XX S MARSHFIELD AVE   110   HOMICIDE      FIRST DEGREE MURDER  False   False     725   7         16    67.0            01A       1166412.0     1862674.0     2022  30-09-2022 15:41  41.778748  -87.665469  (41.77874847, -87.665468981)   23-09-2022  22:31:00    1
                      27076  JF408418     052XX W FERDINAND ST     110   HOMICIDE      FIRST DEGREE MURDER  False   False     1523  15        37    25.0            01A       1141282.0     1902644.0     2022  01-10-2022 15:42  41.888931  -87.756615  (41.88893074, -87.756614969)   24-09-2022  02:35:00    1
                      27077  JF408430     118XX S HALE AVE         110   HOMICIDE      FIRST DEGREE MURDER  True    False     2212  22        34    75.0            01A       1164617.0     1826171.0     2022  16-12-2022 15:40  41.678617  -87.673076  (41.678616627, -87.673076099)  24-09-2022  02:05:00    1
                      27093  JF418383     003XX W 110TH PL         110   HOMICIDE      FIRST DEGREE MURDER  False   False     513   5         34    49.0            01A       1176077.0     1831649.0     2022  08-10-2022 15:41  41.693400  -87.630965  (41.69340045, -87.630964719)   01-10-2022  21:24:00    1
                      27130  JF442641     011XX N HAMLIN AVE       110   HOMICIDE      FIRST DEGREE MURDER  True    True      1112  11        27    23.0            01A       1150839.0     1907309.0     2022  28-10-2022 15:41  41.901550  -87.721395  (41.901550352, -87.721395458)  21-10-2022  04:23:00    1
                      27132  JF445094     005XX N LECLAIRE AVE     110   HOMICIDE      FIRST DEGREE MURDER  False   False     1532  15        37    25.0            01A       1142269.0     1903111.0     2022  29-10-2022 15:41  41.890194  -87.752979  (41.890193984, -87.752978676)  22-10-2022  20:34:00    1
                      27267  JF521130     046XX N LAWNDALE AVE     110   HOMICIDE      FIRST DEGREE MURDER  True    False     1723  17        35    14.0            01A       1150886.0     1930610.0     2022  12-02-2023 15:40  41.965489  -87.720611  (41.965489313, -87.720611147)  23-12-2022  21:04:00    1
                      27305  JG122712     073XX S WABASH AVE       110   HOMICIDE      FIRST DEGREE MURDER  False   False     323   3         6     69.0            01A       1177994.0     1856294.0     2023  27-01-2023 15:42  41.760986  -87.623202  (41.760986379, -87.623201821)  20-01-2023  06:21:00    1
                      27319  JG129690     101XX S WINSTON AVE      110   HOMICIDE      FIRST DEGREE MURDER  True    False     2213  22        34    73.0            01A       1169236.0     1837717.0     2023  18-04-2023 15:40  41.710202  -87.655836  (41.710202355, -87.655836342)  26-01-2023  00:33:00    1
                      27389  JG189597     010XX N CENTRAL AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     1511  15        29    25.0            01A       1138826.0     1906316.0     2023  24-03-2023 15:41  41.899052  -87.765545  (41.899052106, -87.765545247)  17-03-2023  23:31:00    1
                      27411  JG208678     009XX N HAMLIN AVE       110   HOMICIDE      FIRST DEGREE MURDER  False   False     1112  11        27    23.0            01A       1150884.0     1905904.0     2023  09-04-2023 15:42  41.897694  -87.721267  (41.897694011, -87.721266986)  02-04-2023  18:50:00    1
                      27427  JG222358     025XX S TROY ST          110   HOMICIDE      FIRST DEGREE MURDER  False   False     1033  10        12    30.0            01A       1155769.0     1886928.0     2023  20-04-2023 15:41  41.845525  -87.703836  (41.845524863, -87.703835964)  13-04-2023  21:43:00    1
                      27430  JG223397     097XX S BRENNAN AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     431   4         7     51.0            01A       1193246.0     1840556.0     2023  21-04-2023 15:41  41.717441  -87.567816  (41.717440821, -87.567816253)  14-04-2023  17:27:00    1
                      27465  JG249822     081XX S BLACKSTONE AVE   110   HOMICIDE      FIRST DEGREE MURDER  True    False     411   4         8     45.0            01A       1187581.0     1851219.0     2023  13-05-2023 15:41  41.746838  -87.588226  (41.746837554, -87.588226393)  06-05-2023  02:55:00    1
                      27568  JG305608     066XX S EVANS AVE        110   HOMICIDE      FIRST DEGREE MURDER  False   False     321   3         20    42.0            01A       1182360.0     1861161.0     2023  25-06-2023 15:42  41.774242  -87.607050  (41.77424189, -87.607049687)   18-06-2023  08:05:00    1
                      27571  JG306337     083XX S KERFOOT AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     622   6         21    71.0            01A       1173078.0     1849543.0     2023  25-06-2023 15:42  41.742571  -87.641418  (41.74257073, -87.641418175)   18-06-2023  22:06:00    1
                      27626  JG337222     050XX W WASHINGTON BLVD  110   HOMICIDE      FIRST DEGREE MURDER  False   False     1532  15        28    25.0            01A       1142738.0     1900033.0     2023  18-07-2023 15:41  41.881739  -87.751333  (41.881738862, -87.751332935)  11-07-2023  20:15:00    1
                      27652  JG355539     016XX S KARLOV AVE       110   HOMICIDE      FIRST DEGREE MURDER  True    False     1012  10        24    29.0            01A       1149324.0     1891425.0     2023  01-08-2023 15:41  41.857992  -87.727372  (41.857992395, -87.727372203)  25-07-2023  15:35:00    1
                      27679  JG371124     104XX S AVENUE N         110   HOMICIDE      FIRST DEGREE MURDER  False   False     432   4         10    52.0            01A       1201176.0     1836437.0     2023  13-08-2023 15:42  41.705941  -87.538912  (41.705940789, -87.538911828)  06-08-2023  00:48:00    1
                      27680  JG371193     121XX S ASHLAND AVE      110   HOMICIDE      FIRST DEGREE MURDER  True    False     524   5         21    53.0            01A       1167866.0     1824151.0     2023  21-10-2023 15:41  41.673004  -87.661241  (41.673004457, -87.661241159)  06-08-2023  02:00:00    1
                      27692  JG381002     001XX W 109TH PL         110   HOMICIDE      FIRST DEGREE MURDER  False   False     513   5         9     49.0            01A       1177287.0     1832343.0     2023  20-08-2023 15:42  41.695278  -87.626514  (41.695277727, -87.626513815)  13-08-2023  12:28:00    1
                      27704  JG389499     087XX S CREGIER AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     412   4         8     48.0            01A       1189712.0     1847223.0     2023  27-08-2023 15:43  41.735821  -87.580546  (41.735821248, -87.580546071)  19-08-2023  20:42:00    1
                      27706  JG390976     035XX W CONGRESS PKWY    110   HOMICIDE      FIRST DEGREE MURDER  False   False     1133  11        28    27.0            01A       1152981.0     1897468.0     2023  28-08-2023 15:41  41.874503  -87.713789  (41.874503455, -87.713788588)  20-08-2023  23:24:00    1
                      27708  JG392475     015XX S ST LOUIS AVE     110   HOMICIDE      FIRST DEGREE MURDER  False   False     1021  10        24    29.0            01A       1153289.0     1892158.0     2023  29-08-2023 15:42  41.859926  -87.712799  (41.859926121, -87.71279867)   21-08-2023  23:50:00    1
                      27752  JG429927     009XX E 81ST ST          110   HOMICIDE      FIRST DEGREE MURDER  False   False     631   6         8     44.0            01A       1183854.0     1851488.0     2023  27-09-2023 15:43  41.747663  -87.601875  (41.74766347, -87.601874532)   19-09-2023  00:31:00    1
                      27760  JG435639     081XX S THROOP ST        110   HOMICIDE      FIRST DEGREE MURDER  True    False     613   6         17    71.0            01A       1169077.0     1850725.0     2023  03-11-2023 15:41  41.745902  -87.656044  (41.745901647, -87.6560438)    23-09-2023  11:02:00    1
                      27908  JG539116     005XX N LONG AVE         110   HOMICIDE      FIRST DEGREE MURDER  True    True      1523  15        37    25.0            01A       1140225.0     1903244.0     2023  31-12-2023 16:02  41.890597  -87.760482  (41.890596643, -87.760482027)  13-12-2023  06:53:00    1
                      27923  JG552652     087XX S CREGIER AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     412   4         8     48.0            01A       1189712.0     1847219.0     2023  31-12-2023 16:02  41.735810  -87.580546  (41.735810271, -87.580546199)  23-12-2023  21:58:00    1
                      27978  JH150310     011XX E 47TH ST          110   HOMICIDE      FIRST DEGREE MURDER  False   False     222   2         4     39.0            01A       1184539.0     1874072.0     2024  21-02-2024 15:41  41.809620  -87.598658  (41.80961996, -87.598657506)   13-02-2024  01:23:00    1
                      28052  JH204340     069XX S ANTHONY AVE      110   HOMICIDE      FIRST DEGREE MURDER  False   False     322   3         6     69.0            01A       1180698.0     1859288.0     2024  05-04-2024 15:41  41.769141  -87.613200  (41.769140544, -87.613199708)  28-03-2024  12:09:00    1
                      28109  JH257509     039XX N PITTSBURGH AVE   110   HOMICIDE      FIRST DEGREE MURDER  True    False     1631  16        38    17.0            01A       1120353.0     1925182.0     2024  04-06-2024 15:40  41.951138  -87.832993  (41.951138485, -87.832993212)  10-05-2024  09:40:00    1
YMCA                  1142   G610951      050XX S INDIANA AVE      110   HOMICIDE      FIRST DEGREE MURDER  True    False     224   2         3     38.0            01A       1178450.0     1871751.0     2001  01-09-2022 15:42  41.803392  -87.621061  (41.803391597, -87.621061298)  11-10-2001  14:20:00    1
                      3161   HL371794     018XX N LAWNDALE AVE     110   HOMICIDE      FIRST DEGREE MURDER  True    False     2535  25        26    22.0            01A       1151422.0     1911997.0     2005  19-09-2022 15:41  41.914403  -87.719131  (41.914403235, -87.719130719)  22-05-2005  13:40:00    1
                      23817  JB101973     033XX N MARSHFIELD AVE   110   HOMICIDE      FIRST DEGREE MURDER  True    False     1922  19        44    6.0             01A       1164729.0     1922247.0     2018  19-09-2022 15:41  41.942258  -87.669951  (41.942257928, -87.669951491)  12-01-2018  07:00:00    1
Name: count, dtype: int64

In [76]:
# View the top 10 descriptions and their corresponding location descriptions
display(cri[['Description', 'Location Description','Primary Type']].head(50))

# Count the occurrences of each 'Description' and 'Location Description' combination
description_location_counts = cri.groupby(['Description', 'Location Description','Primary Type']).size().reset_index(name='Count')
display(description_location_counts.head(50))

,Description,Location Description,Primary Type
0,TO PROPERTY,OTHER,CRIMINAL DAMAGE
1,FROM BUILDING,APARTMENT,THEFT
2,$500 AND UNDER,STREET,THEFT
3,CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,OFFENSE INVOLVING CHILDREN
4,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,OFFENSE INVOLVING CHILDREN
5,DOMESTIC BATTERY SIMPLE,APARTMENT,BATTERY
6,FORGERY,SIDEWALK,DECEPTIVE PRACTICE
7,COMPUTER FRAUD,RESIDENCE,DECEPTIVE PRACTICE
8,FORCIBLE ENTRY,APARTMENT,BURGLARY
9,$500 AND UNDER,RESIDENCE PORCH/HALLWAY,THEFT
10,HARASSMENT BY TELEPHONE,APARTMENT,OTHER OFFENSE
11,AUTOMOBILE,STREET,MOTOR VEHICLE THEFT
12,INTOXICATING COMPOUNDS,RESIDENCE,OTHER NARCOTIC VIOLATION
13,CRIMINAL DEFACEMENT,RESIDENCE,CRIMINAL DAMAGE
14,NON-AGGRAVATED,STREET,CRIM SEXUAL ASSAULT
15,OVER $500,RESIDENCE,THEFT
16,TO VEHICLE,STREET,CRIMINAL DAMAGE
17,AUTOMOBILE,STREET,MOTOR VEHICLE THEFT
18,SEX OFFENDER - FAIL TO REGISTER,PARK PROPERTY,OTHER OFFENSE
19,TO PROPERTY,STREET,CRIMINAL DAMAGE
20,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,OFFENSE INVOLVING CHILDREN
21,ILLEGAL USE CASH CARD,RESIDENCE,DECEPTIVE PRACTICE
22,SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER,RESIDENCE,OFFENSE INVOLVING CHILDREN
23,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),THEFT
24,$500 AND UNDER,STREET,THEFT
25,OVER $500,RESIDENCE-GARAGE,THEFT
26,AUTOMOBILE,STREET,MOTOR VEHICLE THEFT
27,FORCIBLE ENTRY,RESIDENCE-GARAGE,BURGLARY
28,OVER $500,STREET,THEFT
29,TO PROPERTY,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,CRIMINAL DAMAGE
30,UNLAWFUL ENTRY,GROCERY FOOD STORE,BURGLARY
31,AUTOMOBILE,STREET,MOTOR VEHICLE THEFT
32,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER (SPECIFY),DECEPTIVE PRACTICE
33,OVER $500,STREET,THEFT
34,OVER $500,STREET,THEFT
35,SIMPLE,SIDEWALK,ASSAULT
36,CRIMINAL SEXUAL ABUSE,RESIDENCE,SEX OFFENSE
37,$500 AND UNDER,PARKING LOT / GARAGE (NON RESIDENTIAL),THEFT
38,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,OFFENSE INVOLVING CHILDREN
39,FROM BUILDING,RESIDENCE,THEFT
40,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,DECEPTIVE PRACTICE
41,$500 AND UNDER,RESIDENCE,THEFT
42,AGGRAVATED CRIMINAL SEXUAL ABUSE,SCHOOL - PUBLIC BUILDING,SEX OFFENSE
43,AGG: FINANCIAL ID THEFT,RESIDENCE,THEFT
44,FINANCIAL IDENTITY THEFT OVER $ 300,COMMERCIAL / BUSINESS OFFICE,DECEPTIVE PRACTICE
45,OVER $500,RESIDENCE PORCH/HALLWAY,THEFT
46,OVER $500,RESIDENCE,THEFT
47,HARASSMENT BY TELEPHONE,APARTMENT,OTHER OFFENSE
48,FRAUD OR CONFIDENCE GAME,HOSPITAL BUILDING / GROUNDS,DECEPTIVE PRACTICE
49,NON-AGGRAVATED,RESIDENCE,CRIMINAL SEXUAL ASSAULT

,Description,Location Description,Primary Type,Count
0,$300 AND UNDER,OTHER,THEFT,1
1,$300 AND UNDER,RESIDENCE-GARAGE,THEFT,1
2,$500 AND UNDER,ABANDONED BUILDING,THEFT,14
3,$500 AND UNDER,AIRCRAFT,THEFT,8
4,$500 AND UNDER,AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA,THEFT,5
5,$500 AND UNDER,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,THEFT,5
6,$500 AND UNDER,AIRPORT EXTERIOR - NON-SECURE AREA,THEFT,3
7,$500 AND UNDER,AIRPORT EXTERIOR - SECURE AREA,THEFT,6
8,$500 AND UNDER,AIRPORT PARKING LOT,THEFT,14
9,$500 AND UNDER,AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA,THEFT,11
10,$500 AND UNDER,AIRPORT TERMINAL LOWER LEVEL - SECURE AREA,THEFT,11
11,$500 AND UNDER,AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA,THEFT,3
12,$500 AND UNDER,AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA,THEFT,9
13,$500 AND UNDER,AIRPORT TERMINAL UPPER LEVEL - SECURE AREA,THEFT,23
14,$500 AND UNDER,AIRPORT VENDING ESTABLISHMENT,THEFT,2
15,$500 AND UNDER,AIRPORT/AIRCRAFT,THEFT,354
16,$500 AND UNDER,ALLEY,THEFT,615
17,$500 AND UNDER,ANIMAL HOSPITAL,THEFT,2
18,$500 AND UNDER,APARTMENT,THEFT,3258
19,$500 AND UNDER,APPLIANCE STORE,THEFT,46
20,$500 AND UNDER,ATHLETIC CLUB,THEFT,142
21,$500 AND UNDER,ATM (AUTOMATIC TELLER MACHINE),THEFT,3
22,$500 AND UNDER,AUTO / BOAT / RV DEALERSHIP,THEFT,20
23,$500 AND UNDER,BANK,THEFT,78
24,$500 AND UNDER,BAR OR TAVERN,THEFT,381
25,$500 AND UNDER,BARBERSHOP,THEFT,35
26,$500 AND UNDER,BOAT/WATERCRAFT,THEFT,3
27,$500 AND UNDER,BOWLING ALLEY,THEFT,11
28,$500 AND UNDER,BRIDGE,THEFT,1
29,$500 AND UNDER,CAR WASH,THEFT,38
30,$500 AND UNDER,CEMETARY,THEFT,5
31,$500 AND UNDER,CHA APARTMENT,THEFT,230
32,$500 AND UNDER,CHA HALLWAY / STAIRWELL / ELEVATOR,THEFT,11
33,$500 AND UNDER,CHA HALLWAY/STAIRWELL/ELEVATOR,THEFT,37
34,$500 AND UNDER,CHA PARKING LOT / GROUNDS,THEFT,12
35,$500 AND UNDER,CHA PARKING LOT/GROUNDS,THEFT,104
36,$500 AND UNDER,CHURCH / SYNAGOGUE / PLACE OF WORSHIP,THEFT,27
37,$500 AND UNDER,CHURCH/SYNAGOGUE/PLACE OF WORSHIP,THEFT,138
38,$500 AND UNDER,CLEANING STORE,THEFT,68
39,$500 AND UNDER,COIN OPERATED MACHINE,THEFT,23
40,$500 AND UNDER,COLLEGE / UNIVERSITY - GROUNDS,THEFT,11
41,$500 AND UNDER,COLLEGE / UNIVERSITY - RESIDENCE HALL,THEFT,2
42,$500 AND UNDER,COLLEGE/UNIVERSITY GROUNDS,THEFT,77
43,$500 AND UNDER,COLLEGE/UNIVERSITY RESIDENCE HALL,THEFT,14
44,$500 AND UNDER,COMMERCIAL / BUSINESS OFFICE,THEFT,950
45,$500 AND UNDER,CONSTRUCTION SITE,THEFT,80
46,$500 AND UNDER,CONVENIENCE STORE,THEFT,69
47,$500 AND UNDER,CTA BUS,THEFT,240
48,$500 AND UNDER,CTA BUS STOP,THEFT,23
49,$500 AND UNDER,CTA PARKING LOT / GARAGE / OTHER PROPERTY,THEFT,11

In [77]:
cri.to_csv('crime_50.csv', index=False)

In [42]:
description_location_counts = cri.groupby(['Block','Description', 'Location Description']).size().reset_index(name='Count')
display(description_location_counts)

,Block,Description,Location Description,Count
0,0000X E 100 PL,$500 AND UNDER,RESIDENCE,2
1,0000X E 100 PL,$500 AND UNDER,STREET,1
2,0000X E 100 PL,AGGRAVATED: OTHER DANG WEAPON,STREET,1
3,0000X E 100 PL,AGGRAVATED:KNIFE/CUTTING INSTR,RESIDENCE,1
4,0000X E 100 PL,ATT: AUTOMOBILE,STREET,1
...,...,...,...,...
405497,137XX S LEYDEN AV,UNLAWFUL ENTRY,OTHER,1
405498,137XX S LEYDEN AVE,AGGRAVATED,APARTMENT,1
405499,137XX S LEYDEN AVE,AGGRAVATED - HANDGUN,OTHER (SPECIFY),1
405500,137XX S LEYDEN AVE,FIRST DEGREE MURDER,STREET,1
405501,137XX S LEYDEN AVE,TO PROPERTY,RESIDENCE,1

In [49]:
# Count unique Location Descriptions for each Description
description_location_counts = cri.groupby('Description')['Location Description'].nunique().reset_index()

# Rename columns for clarity
description_location_counts.columns = ['Description', 'Unique Location Description Count']

# Display the results
display(description_location_counts.sort_values(by='Unique Location Description Count', ascending=True).head(10))
display(description_location_counts.sort_values(by='Unique Location Description Count', ascending=True).tail(10))

,Description,Unique Location Description Count
447,WIREROOM/HORSES,1
40,AGGRAVATED OF AN UNBORN CHILD,1
260,MANUFACTURE / DELIVER - LOOK-ALIKE DRUG,1
267,MONEY LAUNDERING,1
270,NON-CONSENSUAL DISSEMINATION PRIVATE SEXUAL IM...,1
3,ADULTRY,1
354,SALE/DIST OBSCENE MAT TO MINOR,1
363,SEX OFFENDER: PROHIBITED ZONE,1
80,ATT AGG CRIM SEXUAL ABUSE,1
383,"THEFT / RECOVERY - CYCLE, SCOOTER, BIKE NO VIN",1

                  Description  Unique Location Description Count
381          TELEPHONE THREAT                                 87
190       FIRST DEGREE MURDER                                 89
192            FORCIBLE ENTRY                                 90
197  FRAUD OR CONFIDENCE GAME                                 95
401                   TO LAND                                105
407                TO VEHICLE                                106
402               TO PROPERTY                                117
1              $500 AND UNDER                                126
290                 OVER $500                                126
368                    SIMPLE                                129

In [35]:
# Count unique Location Descriptions for each Primary Type
primary_type_location_counts = cri.groupby('Primary Type')['Location Description'].nunique().reset_index()

# Rename columns for clarity
primary_type_location_counts.columns = ['Primary Type', 'Unique Location Description Count']

# Display the results
print("Top 10 Primary Types with the fewest unique Location Descriptions:")
display(primary_type_location_counts.sort_values(by='Unique Location Description Count', ascending=True).head(10))

print("Top 10 Primary Types with the most unique Location Descriptions:")
display(primary_type_location_counts.sort_values(by='Unique Location Description Count', ascending=False).head(10))

Top 10 Primary Types with the fewest unique Location Descriptions:

                         Primary Type  Unique Location Description Count
10                  DOMESTIC VIOLENCE                                  1
20                       NON-CRIMINAL                                  2
28                          RITUALISM                                  4
13                  HUMAN TRAFFICKING                                  5
23           OTHER NARCOTIC VIOLATION                                  7
26                   PUBLIC INDECENCY                                 10
21                          OBSCENITY                                 13
4   CONCEALED CARRY LICENSE VIOLATION                                 20
25                       PROSTITUTION                                 24
11                           GAMBLING                                 28

Top 10 Primary Types with the most unique Location Descriptions:

              Primary Type  Unique Location Description Count
32                   THEFT                                132
2                  BATTERY                                130
6          CRIMINAL DAMAGE                                127
9       DECEPTIVE PRACTICE                                121
1                  ASSAULT                                118
8        CRIMINAL TRESPASS                                117
24           OTHER OFFENSE                                113
29                 ROBBERY                                100
19               NARCOTICS                                 99
27  PUBLIC PEACE VIOLATION                                 97

In [31]:
cri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549434 entries, 0 to 549433
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549434 non-null  int64
 1   Case Number           549434 non-null  object
 2   Block                 549434 non-null  object
 3   IUCR                  549434 non-null  object
 4   Primary Type          549434 non-null  object
 5   Description           549434 non-null  object
 6   Location Description  547761 non-null  object
 7   Arrest                549434 non-null  bool
 8   Domestic              549434 non-null  bool
 9   Beat                  549434 non-null  int64
 10  District              549434 non-null  int64
 11  Ward                  549434 non-null  int64
 12  Community Area        549434 non-null  float64
 13  FBI Code              549434 non-null  object
 14  X Coordinate          549434 non-null  float64
 15  Y Coordinate          549434 non-null  float64
 16  Year                  549434 non-null  int64
 17  Updated On            549434 non-null  object
 18  Latitude              549434 non-null  float64
 19  Longitude             549434 non-null  float64
 20  Location              542522 non-null  object
 21  DATE                  549434 non-null  object
 22  TIME                  549434 non-null  object
dtypes: bool(2), float64(5), int64(5), object(11)
memory usage: 89.1+ MB

In [20]:
# Filter descriptions that map to only one unique Location Description
single_location_descriptions = description_location_counts[description_location_counts['Unique Location Description Count'] == 56]

# Display those descriptions
display(single_location_descriptions)

                        Description  Unique Location Description Count
18                       AGGRAVATED                                 56
107          ATTEMPT FORCIBLE ENTRY                                 56
206  HARASSMENT BY ELECTRONIC MEANS                                 56
378          STRONG ARM - NO WEAPON                                 56
416   UNLAWFUL POSSESSION - HANDGUN                                 56

In [47]:
# Find rows with NaN in Location Description
missing_location_by_description = cri[cri['Location Description'].isna()].groupby('Description').size().reset_index(name='Missing Count')

# Display top missing descriptions
display(missing_location_by_description.sort_values(by='Missing Count', ascending=False).head(60))

Empty DataFrame
Columns: [Description, Missing Count]
Index: []

In [45]:
cri['Location Description'].count()

np.int64(549434)

In [44]:
# Count Location Descriptions per IUCR Code
iucr_location_counts = cri.groupby('Block')['Location Description'].value_counts().reset_index(name='Count')

# Count Location Descriptions per FBI Code
# fbi_location_counts = cri.groupby('FBI Code')['Location Description'].value_counts().reset_index(name='Count')

# Display the top 10 IUCR locations and FBI Code locations
print("Top 10 IUCR Code with Location Descriptions:")
display(iucr_location_counts.head(50))

Top 10 IUCR Code with Location Descriptions:

               Block             Location Description  Count
0     0000X E 100 PL                           STREET      9
1     0000X E 100 PL                        RESIDENCE      7
2     0000X E 100 PL                        APARTMENT      2
3     0000X E 100 PL                         SIDEWALK      2
4     0000X E 100 PL                            ALLEY      1
5     0000X E 100 ST                        RESIDENCE     14
6     0000X E 100 ST                           STREET      4
7     0000X E 100 ST                        APARTMENT      2
8     0000X E 100 ST   PARKING LOT/GARAGE(NON.RESID.)      1
9     0000X E 100 ST                 RESIDENCE-GARAGE      1
10    0000X E 100 ST         SCHOOL, PRIVATE, GROUNDS      1
11    0000X E 100 ST                         SIDEWALK      1
12  0000X E 100TH PL                        RESIDENCE      3
13  0000X E 100TH PL                           STREET      2
14  0000X E 100TH PL                        APARTMENT      1
15  0000X E 100TH PL  RESIDENCE - YARD (FRONT / BACK)      1
16  0000X E 100TH ST                        RESIDENCE      4
17  0000X E 100TH ST                           STREET      2
18  0000X E 100TH ST                            ALLEY      1
19  0000X E 100TH ST                        APARTMENT      1
20  0000X E 100TH ST                      GAS STATION      1
21  0000X E 100TH ST                         SIDEWALK      1
22    0000X E 101 PL                        RESIDENCE      2
23    0000X E 101 PL               ABANDONED BUILDING      1
24    0000X E 101 PL                           STREET      1
25    0000X E 101 ST                        RESIDENCE      9
26    0000X E 101 ST                           STREET      4
27    0000X E 101 ST                            ALLEY      2
28    0000X E 101 ST                            OTHER      1
29    0000X E 101 ST                 RESIDENCE-GARAGE      1
30  0000X E 101ST PL                        RESIDENCE      5
31  0000X E 101ST PL                           STREET      5
32  0000X E 101ST PL                            ALLEY      1
33  0000X E 101ST PL                        APARTMENT      1
34  0000X E 101ST PL  RESIDENCE - YARD (FRONT / BACK)      1
35  0000X E 101ST ST                           STREET      3
36  0000X E 101ST ST                        RESIDENCE      2
37  0000X E 101ST ST                        APARTMENT      1
38  0000X E 101ST ST                         SIDEWALK      1
39    0000X E 102 PL                        RESIDENCE      6
40    0000X E 102 PL                           STREET      4
41    0000X E 102 PL               ABANDONED BUILDING      1
42    0000X E 102 ST                        RESIDENCE      7
43    0000X E 102 ST                         SIDEWALK      2
44    0000X E 102 ST                           STREET      2
45  0000X E 102ND PL                        RESIDENCE      2
46  0000X E 102ND PL                            OTHER      1
47  0000X E 102ND PL                           STREET      1
48  0000X E 102ND ST                           STREET      6
49  0000X E 102ND ST                        RESIDENCE      3

In [40]:
# Create a mapping of Description to most common Location Description
location_mapping = cri.groupby('Description')['Location Description'].agg(
    lambda x: x.value_counts().index[0] if len(x.dropna()) > 0 else None
).to_dict()

# Remove None values from mapping
location_mapping = {k: v for k, v in location_mapping.items() if v is not None}

# Fill NaNs using the mapping
cri['Location Description'] = cri.apply(
    lambda row: location_mapping.get(row['Description'], row['Location Description'])
    if pd.isna(row['Location Description'])
    else row['Location Description'],
    axis=1
)

# Fill any remaining NaNs with overall mode
overall_mode_location = cri['Location Description'].dropna().mode()[0] if not cri['Location Description'].dropna().empty else "Unknown"
cri['Location Description'].fillna(overall_mode_location, inplace=True)

C:\Users\krebi\AppData\Local\Temp\ipykernel_14096\2817846352.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cri['Location Description'].fillna(overall_mode_location, inplace=True)

In [17]:
a=cri.iloc[:5,:1]
display(a)

         ID
0   1410349
1  12943357
2   1387139
3  13277780
4  12893837

In [18]:

cri.drop(columns=['ID', 'Case Number', 'X Coordinate', 'Y Coordinate', 'Location'], inplace=True)
cri.drop(columns=['Updated On'],inplace=True)
cri.drop(columns=['Description'],inplace=True)
cri.head(5)

,Block,IUCR,Primary Type,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Year,Latitude,Longitude,DATE,TIME
0,065XX S WESTERN AV,1310,CRIMINAL DAMAGE,OTHER,False,False,832,8,22,30.0,14,2001,41.775116,-87.683386,04-03-2001,00:00:00
1,029XX S DR MARTIN LUTHER KING JR DR,890,THEFT,APARTMENT,False,False,133,1,4,35.0,6,2022,41.841623,-87.617191,19-12-2022,00:00:00
2,030XX W WABANSIA AV,820,THEFT,STREET,False,False,1421,14,22,30.0,6,2001,41.912095,-87.702352,18-01-2001,00:00:00
3,011XX W NEWPORT AVE,1751,OFFENSE INVOLVING CHILDREN,APARTMENT,False,True,1924,19,44,6.0,17,2013,41.944428,-87.657553,01-06-2013,00:00:00
4,024XX W 48TH ST,1752,OFFENSE INVOLVING CHILDREN,RESIDENCE,False,True,922,9,15,58.0,17,2022,41.806597,-87.685577,09-11-2022,00:00:00

In [19]:
print(cri['Block'].head())
cri.shape

0                     065XX S WESTERN AV
1    029XX S DR MARTIN LUTHER KING JR DR
2                    030XX W WABANSIA AV
3                    011XX W NEWPORT AVE
4                        024XX W 48TH ST
Name: Block, dtype: object

(549434, 16)

In [20]:
print(cri.columns)

Index(['Block', 'IUCR', 'Primary Type', 'Location Description', 'Arrest',
       'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code',
       'Year', 'Latitude', 'Longitude', 'DATE', 'TIME'],
      dtype='object')

In [22]:
import pandas as pd

# Ensure DATE is in datetime format
cri['DATE'] = pd.to_datetime(cri['DATE'], format='%d-%m-%Y', errors='coerce')

In [24]:
# Sort dataset by DATE and TIME
cri = cri.sort_values(by=['DATE', 'TIME']).reset_index(drop=True)

In [25]:
# Extract Day, Week, and Month from DATE
cri['Day'] = cri['DATE'].dt.day_name()  # e.g., Monday, Tuesday
cri['Week'] = cri['DATE'].dt.isocalendar().week  # ISO week number
cri['Month'] = cri['DATE'].dt.month_name()  # e.g., January, February

In [31]:
cri.tail(50)

,Block,IUCR,Primary Type,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Year,Latitude,Longitude,DATE,TIME,Day,Week,Month
549384,091XX S BURNSIDE AVE,820,THEFT,RESIDENCE,False,False,633,6,6,49.0,6,2024,41.728099,-87.617127,2024-05-29,22:45:00,Wednesday,22,May
549385,007XX N CHRISTIANA AVE,498,BATTERY,SIDEWALK,False,True,1121,11,27,23.0,04B,2024,41.894539,-87.710187,2024-05-29,22:54:00,Wednesday,22,May
549386,095XX S STATE ST,486,BATTERY,OTHER (SPECIFY),True,True,511,5,9,49.0,08B,2024,41.721181,-87.623717,2024-05-29,22:54:00,Wednesday,22,May
549387,001XX E Wacker Dr,2826,OTHER OFFENSE,HOTEL / MOTEL,False,False,114,1,42,32.0,26,2024,41.888165,-87.622937,2024-05-29,22:55:00,Wednesday,22,May
549388,059XX S THROOP ST,460,BATTERY,RESIDENCE,False,False,713,7,16,67.0,08B,2024,41.786117,-87.657095,2024-05-29,23:00:00,Wednesday,22,May
549389,008XX N RICHMOND ST,820,THEFT,SIDEWALK,False,True,1211,12,26,24.0,6,2024,41.897296,-87.700415,2024-05-29,23:00:00,Wednesday,22,May
549390,029XX S MICHIGAN AVE,810,THEFT,STREET,False,False,133,1,3,35.0,6,2024,41.840817,-87.623516,2024-05-29,23:00:00,Wednesday,22,May
549391,015XX W SHERWIN AVE,486,BATTERY,APARTMENT,False,True,2423,24,49,1.0,08B,2024,42.014951,-87.668865,2024-05-29,23:00:00,Wednesday,22,May
549392,002XX S CANAL ST,1220,DECEPTIVE PRACTICE,OTHER RAILROAD PROPERTY / TRAIN DEPOT,False,False,121,1,42,28.0,11,2024,41.878646,-87.639578,2024-05-29,23:00:00,Wednesday,22,May
549393,076XX S NORMAL AVE,910,MOTOR VEHICLE THEFT,STREET,False,False,621,6,17,69.0,7,2024,41.755257,-87.636847,2024-05-29,23:00:00,Wednesday,22,May
549394,002XX W 116TH ST,430,BATTERY,APARTMENT,False,True,522,5,9,53.0,04B,2024,41.683423,-87.629254,2024-05-29,23:00:00,Wednesday,22,May
549395,015XX S KEDZIE AVE,910,MOTOR VEHICLE THEFT,STREET,False,False,1022,10,24,29.0,7,2024,41.860520,-87.705502,2024-05-29,23:00:00,Wednesday,22,May
549396,001XX W 105TH ST,1310,CRIMINAL DAMAGE,STREET,False,False,512,5,9,49.0,14,2024,41.703470,-87.627409,2024-05-29,23:01:00,Wednesday,22,May
549397,028XX N MILWAUKEE AVE,820,THEFT,RESTAURANT,False,False,1412,14,35,21.0,6,2024,41.933058,-87.713946,2024-05-29,23:03:00,Wednesday,22,May
549398,068XX S PERRY AVE,488,BATTERY,STREET,False,True,722,7,6,69.0,04B,2024,41.770244,-87.628294,2024-05-29,23:05:00,Wednesday,22,May
549399,081XX S SAGINAW AVE,910,MOTOR VEHICLE THEFT,STREET,False,False,422,4,7,46.0,7,2024,41.747557,-87.560100,2024-05-29,23:05:00,Wednesday,22,May
549400,072XX S CONSTANCE AVE,486,BATTERY,APARTMENT,False,True,324,3,7,43.0,08B,2024,41.763080,-87.580521,2024-05-29,23:06:00,Wednesday,22,May
549401,006XX N MICHIGAN AVE,1310,CRIMINAL DAMAGE,ATHLETIC CLUB,False,False,1834,18,42,8.0,14,2024,41.893535,-87.624222,2024-05-29,23:07:00,Wednesday,22,May
549402,080XX S WESTERN AVE,910,MOTOR VEHICLE THEFT,STREET,False,False,835,8,18,70.0,7,2024,41.748062,-87.682802,2024-05-29,23:15:00,Wednesday,22,May
549403,076XX N SHERIDAN RD,520,ASSAULT,APARTMENT,False,True,2422,24,49,1.0,04A,2024,42.020648,-87.666451,2024-05-29,23:25:00,Wednesday,22,May
549404,111XX S WALLACE ST,051A,ASSAULT,STREET,False,False,2233,22,21,49.0,04A,2024,41.691681,-87.637512,2024-05-29,23:26:00,Wednesday,22,May
549405,001XX E 90TH ST,141B,WEAPONS VIOLATION,STREET,False,False,634,6,6,44.0,15,2024,41.730920,-87.620144,2024-05-29,23:28:00,Wednesday,22,May
549406,014XX W 15TH ST,910,MOTOR VEHICLE THEFT,STREET,False,False,1233,12,28,28.0,7,2024,41.861524,-87.662105,2024-05-29,23:30:00,Wednesday,22,May
549407,008XX N FAIRFIELD AVE,486,BATTERY,APARTMENT,False,True,1211,12,36,24.0,08B,2024,41.896352,-87.695488,2024-05-29,23:30:00,Wednesday,22,May
549408,044XX N KEOKUK AVE,930,MOTOR VEHICLE THEFT,RESIDENCE,False,False,1722,17,39,16.0,7,2024,41.962302,-87.733441,2024-05-29,23:30:00,Wednesday,22,May
549409,004XX N LAWLER AVE,051A,ASSAULT,STREET,False,False,1532,15,37,25.0,04A,2024,41.888395,-87.751691,2024-05-29,23:30:00,Wednesday,22,May
549410,030XX N KEATING AVE,520,ASSAULT,APARTMENT,True,True,2521,25,31,19.0,04A,2024,41.935804,-87.745494,2024-05-29,23:30:00,Wednesday,22,May
549411,079XX S KENWOOD AVE,486,BATTERY,RESIDENCE,False,True,411,4,8,45.0,08B,2024,41.750747,-87.591820,2024-05-29,23:33:00,Wednesday,22,May
549412,040XX W 58TH PL,486,BATTERY,RESIDENCE,False,True,813,8,13,62.0,08B,2024,41.786833,-87.724273,2024-05-29,23:36:00,Wednesday,22,May
549413,131XX S LANGLEY AVE,1320,CRIMINAL DAMAGE,APARTMENT,False,True,533,5,10,54.0,14,2024,41.656581,-87.605131,2024-05-29,23:44:00,Wednesday,22,May
549414,070XX S COTTAGE GROVE AVE,2093,NARCOTICS,POLICE FACILITY / VEHICLE PARKING LOT,False,False,321,3,6,42.0,18,2024,41.766804,-87.605620,2024-05-29,23:45:00,Wednesday,22,May
549415,106XX S AVENUE F,1310,CRIMINAL DAMAGE,RESIDENCE,False,False,432,4,10,52.0,14,2024,41.702051,-87.530449,2024-05-29,23:50:00,Wednesday,22,May
549416,066XX S SEELEY AVE,486,BATTERY,RESIDENCE,False,True,726,7,16,67.0,08B,2024,41.773238,-87.674959,2024-05-29,23:55:00,Wednesday,22,May
549417,015XX E 67TH PL,1320,CRIMINAL DAMAGE,DRIVEWAY - RESIDENTIAL,False,False,332,3,5,43.0,14,2024,41.772417,-87.587329,2024-05-29,23:59:00,Wednesday,22,May
549418,054XX S BISHOP ST,2826,OTHER OFFENSE,RESIDENCE,False,False,934,9,16,61.0,26,2024,41.795062,-87.660972,2024-05-30,00:00:00,Thursday,22,May
549419,091XX S PRINCETON AVE,820,THEFT,RESIDENCE,False,False,634,6,9,49.0,6,2024,41.727713,-87.630097,2024-05-30,00:00:00,Thursday,22,May
549420,100XX S LA SALLE ST,1310,CRIMINAL DAMAGE,RESIDENCE - GARAGE,False,False,511,5,9,49.0,14,2024,41.711792,-87.627227,2024-05-30,00:00:00,Thursday,22,May
549421,091XX S PRINCETON AVE,1150,DECEPTIVE PRACTICE,RESIDENCE,False,False,634,6,9,49.0,11,2024,41.727713,-87.630097,2024-05-30,00:00:00,Thursday,22,May
549422,006XX N PINE AVE,920,MOTOR VEHICLE THEFT,STREET,False,False,1524,15,37,25.0,7,2024,41.891624,-87.763437,2024-05-30,00:00:00,Thursday,22,May
549423,005XX W 64TH ST,910,MOTOR VEHICLE THEFT,STREET,False,False,722,7,6,68.0,7,2024,41.778034,-87.637957,2024-05-30,00:00:00,Thursday,22,May
549424,132XX S BURLEY AVE,560,ASSAULT,SCHOOL - PUBLIC BUILDING,False,False,433,4,10,55.0,08A,2024,41.654766,-87.544723,2024-05-30,00:00:00,Thursday,22,May
549425,061XX S DR MARTIN LUTHER KING JR DR,1320,CRIMINAL DAMAGE,SIDEWALK,False,True,313,3,20,42.0,14,2024,41.782932,-87.615693,2024-05-30,00:00:00,Thursday,22,May
549426,026XX W EVERGREEN AVE,281,CRIMINAL SEXUAL ASSAULT,RESIDENCE,False,False,1423,14,26,24.0,2,2024,41.905699,-87.693139,2024-05-30,00:00:00,Thursday,22,May
549427,089XX S MUSKEGON AVE,930,MOTOR VEHICLE THEFT,STREET,False,False,423,4,10,46.0,7,2024,41.732979,-87.555476,2024-05-30,00:00:00,Thursday,22,May
549428,001XX S MAYFIELD AVE,820,THEFT,RESIDENCE - YARD (FRONT / BACK),False,False,1513,15,29,25.0,6,2024,41.878556,-87.771334,2024-05-30,00:00:00,Thursday,22,May
549429,100XX S EMERALD AVE,610,BURGLARY,RESIDENCE,False,False,2232,22,21,73.0,5,2024,41.711760,-87.641745,2024-05-30,00:00:00,Thursday,22,May
549430,039XX W DIVISION ST,560,ASSAULT,GAS STATION,True,False,2535,25,37,23.0,08A,2024,41.902679,-87.725602,2024-05-30,00:00:00,Thursday,22,May
549431,018XX S UNION AVE,910,MOTOR VEHICLE THEFT,STREET,False,False,1235,12,25,31.0,7,2024,41.857307,-87.644779,2024-05-30,00:00:00,Thursday,22,May
549432,066XX S MARYLAND AVE,1153,DECEPTIVE PRACTICE,APARTMENT,False,False,321,3,20,42.0,11,2024,41.774073,-87.604573,2024-05-30,00:00:00,Thursday,22,May
549433,029XX N LINCOLN AVE,610,BURGLARY,SMALL RETAIL STORE,False,False,1933,19,32,6.0,5,2024,41.935308,-87.662555,2024-05-30,00:00:00,Thursday,22,May

In [30]:
cri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549434 entries, 0 to 549433
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Block                 549434 non-null  object
 1   IUCR                  549434 non-null  object
 2   Primary Type          549434 non-null  object
 3   Location Description  549434 non-null  object
 4   Arrest                549434 non-null  bool
 5   Domestic              549434 non-null  bool
 6   Beat                  549434 non-null  int64
 7   District              549434 non-null  int64
 8   Ward                  549434 non-null  int64
 9   Community Area        549434 non-null  float64
 10  FBI Code              549434 non-null  object
 11  Year                  549434 non-null  int64
 12  Latitude              549434 non-null  float64
 13  Longitude             549434 non-null  float64
 14  DATE                  549434 non-null  datetime64[ns]
 15  TIME                  549434 non-null  object
 16  Day                   549434 non-null  object
 17  Week                  549434 non-null  UInt32
 18  Month                 549434 non-null  object
dtypes: UInt32(1), bool(2), datetime64[ns](1), float64(3), int64(4), object(8)
memory usage: 70.7+ MB

In [32]:
cri.to_csv('crime_100.csv', index=False)

In [40]:
A=cri[cri['IUCR']== '460']
display(A)

,Block,IUCR,Primary Type,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,Year,Latitude,Longitude,DATE,TIME,Day,Week,Month
14,078XX S ESSEX AV,460,BATTERY,RESIDENCE,False,False,421,4,22,30.0,08B,2001,41.753316,-87.563985,2001-01-01,00:00:00,Monday,1,January
54,023XX S STATE ST,460,BATTERY,CHA HALLWAY/STAIRWELL/ELEVATOR,False,True,2113,2,3,33.0,08B,2001,41.850123,-87.627172,2001-01-01,00:01:00,Monday,1,January
99,020XX W 69 ST,460,BATTERY,RESIDENCE PORCH/HALLWAY,False,True,735,7,22,30.0,08B,2001,41.768317,-87.674881,2001-01-01,00:05:00,Monday,1,January
103,016XX S CENTRAL PARK AV,460,BATTERY,RESIDENCE,False,True,1021,10,22,30.0,08B,2001,41.857334,-87.715019,2001-01-01,00:10:00,Monday,1,January
113,020XX W 17 ST,460,BATTERY,SIDEWALK,False,False,1223,12,22,30.0,08B,2001,41.858408,-87.678028,2001-01-01,00:20:00,Monday,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549311,015XX N DAMEN AVE,460,BATTERY,CTA TRAIN,False,False,1424,14,1,24.0,08B,2024,41.909730,-87.677445,2024-05-29,20:40:00,Wednesday,22,May
549332,033XX N NORMANDY AVE,460,BATTERY,STREET,False,False,1632,16,38,17.0,08B,2024,41.941404,-87.793380,2024-05-29,21:11:00,Wednesday,22,May
549346,027XX W NORTH SHORE AVE,460,BATTERY,APARTMENT,False,True,2412,24,50,2.0,08B,2024,42.003031,-87.699085,2024-05-29,21:31:00,Wednesday,22,May
549349,003XX E 51ST ST,460,BATTERY,CTA TRAIN,False,False,231,2,3,40.0,08B,2024,41.802065,-87.618641,2024-05-29,21:41:00,Wednesday,22,May
549388,059XX S THROOP ST,460,BATTERY,RESIDENCE,False,False,713,7,16,67.0,08B,2024,41.786117,-87.657095,2024-05-29,23:00:00,Wednesday,22,May